#ifndef __BBOX_DDR_FIELD_H_
#define __BBOX_DDR_FIELD_H_

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus


/* FIELD_OUTPUT_TYPE_BIN
 * key:
 * 0x00000000 FFFF FFFF FFFF FFFF
 * 0x00000010 FFFF FFFF FFFF FFFF
 *
 * FIELD_OUTPUT_TYPE_STR
 * key: qwertyuiop
 *
 * FIELD_OUTPUT_TYPE_STR_NL
 * key: 
 * qwertyuiop
 *
 * FIELD_OUTPUT_TYPE_HEX
 * key: FFFFFFFFFFFFFFFF
 *
 * FIELD_OUTPUT_TYPE_INT
 * key: 0xFF
 */
#define FIELD_OUTPUT_TYPE_BIN    1          //整片二进制输出，按16进制显示
#define FIELD_OUTPUT_TYPE_STR    2          //换行字符串输出
#define FIELD_OUTPUT_TYPE_STR_NL 3          //不换行字符串输出
#define FIELD_OUTPUT_TYPE_HEX    4          //每个字节按hex输出，最多输出16个字节
#define FIELD_OUTPUT_TYPE_INT    5          //1,2,4,8字节整型输出
#define FIELD_OUTPUT_TYPE_CHAR   6          //按长度，字符输出

#define FIELD_OUTPUT_HEX_MAX_LEN    16
#define FIELD_NAME_MAX_LEN          32
#define FIELD_OUTPUT_CHAR_LEN       1
#define FIELD_OUTPUT_SHORT_LEN      2
#define FIELD_OUTPUT_INT_LEN        4
#define FIELD_OUTPUT_LONG_LEN       8

typedef struct{
    char field_name[FIELD_NAME_MAX_LEN];
    unsigned char type;
    unsigned int offset;
    unsigned int len;
} ddr_field_s;
#define DDR_FIELD_DESCRIPTION_VECTOR(MODULE_NAME) ddr_field_s DDR_FIELD_DESCRIPTION_VECTOR_OBJECT_##MODULE_NAME

#define GET_VECTOR_TABLE(MODULE_NAME)   &DDR_FIELD_DESCRIPTION_VECTOR_OBJECT_##MODULE_NAME[0]
#define GET_VECTOR_ITEM(MODULE_NAME, i) &DDR_FIELD_DESCRIPTION_VECTOR_OBJECT_##MODULE_NAME[i]
#define GET_VECTOR_NUM(MODULE_NAME)     (sizeof(DDR_FIELD_DESCRIPTION_VECTOR_OBJECT_##MODULE_NAME)/sizeof(ddr_field_s))

/*each Module need define as follows*/
/* LPM3 module */
#define FIELD_DESCRIPTION_LPM3_START DDR_FIELD_DESCRIPTION_VECTOR(LPM3_START)[]= {\
    {"start_step 1", FIELD_OUTPUT_TYPE_INT, 0x0, 0x1}, \
    {"start_step 2", FIELD_OUTPUT_TYPE_INT, 0x1, 0x1}, \
    {"start_step 3", FIELD_OUTPUT_TYPE_INT, 0x2, 0x1}, \
    {"start_step 4", FIELD_OUTPUT_TYPE_INT, 0x3, 0x1}, \
    {"start_step 5", FIELD_OUTPUT_TYPE_INT, 0x4, 0x1}, \
    {"start_step 6", FIELD_OUTPUT_TYPE_INT, 0x5, 0x1}, \
    {"start_step 7", FIELD_OUTPUT_TYPE_INT, 0x6, 0x1}, \
    {"start_step 8", FIELD_OUTPUT_TYPE_INT, 0x7, 0x1}, \
    {"start_step 9", FIELD_OUTPUT_TYPE_INT, 0x8, 0x1}, \
    {"start_step 10", FIELD_OUTPUT_TYPE_INT, 0x9, 0x1}, \
    {"start_step 11", FIELD_OUTPUT_TYPE_INT, 0xa, 0x1}, \
    {"start_step 12", FIELD_OUTPUT_TYPE_INT, 0xb, 0x1}, \
    {"start_step 13", FIELD_OUTPUT_TYPE_INT, 0xc, 0x1}, \
    {"start_step 14", FIELD_OUTPUT_TYPE_INT, 0xd, 0x1}, \
    {"start_step 15", FIELD_OUTPUT_TYPE_INT, 0xe, 0x1}, \
    {"start_step 16", FIELD_OUTPUT_TYPE_INT, 0xf, 0x1}, \
    {"start_step 17", FIELD_OUTPUT_TYPE_INT, 0x10, 0x1}, \
    {"start_step 18", FIELD_OUTPUT_TYPE_INT, 0x11, 0x1}, \
    {"start_step 19", FIELD_OUTPUT_TYPE_INT, 0x12, 0x1}, \
    {"start_step 20", FIELD_OUTPUT_TYPE_INT, 0x13, 0x1}, \
    {"start_step 21", FIELD_OUTPUT_TYPE_INT, 0x14, 0x1}, \
    {"start_step 22", FIELD_OUTPUT_TYPE_INT, 0x15, 0x1}, \
    {"start_step 23", FIELD_OUTPUT_TYPE_INT, 0x16, 0x1}, \
    {"start_step 24", FIELD_OUTPUT_TYPE_INT, 0x17, 0x1}, \
    {"start_step 25", FIELD_OUTPUT_TYPE_INT, 0x18, 0x1}, \
    {"start_step 26", FIELD_OUTPUT_TYPE_INT, 0x19, 0x1}, \
    {"start_step 27", FIELD_OUTPUT_TYPE_INT, 0x1a, 0x1}, \
}

#define FIELD_DESCRIPTION_LPM3  DDR_FIELD_DESCRIPTION_VECTOR(LPM3)[]= {\
    {"****exc****reg**", FIELD_OUTPUT_TYPE_STR, 0x00, 0x8}, \
    {"reset_reason", FIELD_OUTPUT_TYPE_INT, 0x80, 0x4}, \
    {"slice", FIELD_OUTPUT_TYPE_INT, 0x80, 0x4}, \
    {"rtc", FIELD_OUTPUT_TYPE_INT, 0x84, 0x4}, \
    {"r13", FIELD_OUTPUT_TYPE_INT, 0x88, 0x4}, \
    {"lr1", FIELD_OUTPUT_TYPE_INT, 0x8c, 0x4}, \
    {"pc", FIELD_OUTPUT_TYPE_INT, 0x90, 0x4}, \
    {"xpsr", FIELD_OUTPUT_TYPE_INT, 0x94, 0x4}, \
    {"cfsr", FIELD_OUTPUT_TYPE_INT, 0x98, 0x4}, \
    {"hfsr", FIELD_OUTPUT_TYPE_INT, 0x9c, 0x4}, \
    {"bfar", FIELD_OUTPUT_TYPE_INT, 0xa0, 0x4}, \
    {"exc_trace", FIELD_OUTPUT_TYPE_INT, 0xa4, 0x1}, \
    {"ddr_exc", FIELD_OUTPUT_TYPE_INT, 0xa5, 0x1}, \
    {"irq_id", FIELD_OUTPUT_TYPE_INT, 0xa6, 0x2}, \
    {"task_id", FIELD_OUTPUT_TYPE_INT, 0xa8, 0x4}, \
    {"**backup**reg***", FIELD_OUTPUT_TYPE_STR, 0x00, 0x8}, \
    {"reg_backup_index", FIELD_OUTPUT_TYPE_INT, 0x200, 0x4}, \
    {"reason_0", FIELD_OUTPUT_TYPE_INT, 0x204, 0x4}, \
    {"reason_1", FIELD_OUTPUT_TYPE_INT, 0x208, 0x4}, \
    {"reason_2", FIELD_OUTPUT_TYPE_INT, 0x20C, 0x4}, \
    {"r0", FIELD_OUTPUT_TYPE_INT, 0x210, 0x4}, \
    {"r1", FIELD_OUTPUT_TYPE_INT, 0x214, 0x4}, \
    {"r2", FIELD_OUTPUT_TYPE_INT, 0x218, 0x4}, \
    {"r3", FIELD_OUTPUT_TYPE_INT, 0x21c, 0x4}, \
    {"r4", FIELD_OUTPUT_TYPE_INT, 0x220, 0x4}, \
    {"r5", FIELD_OUTPUT_TYPE_INT, 0x224, 0x4}, \
    {"r6", FIELD_OUTPUT_TYPE_INT, 0x228, 0x4}, \
    {"r7", FIELD_OUTPUT_TYPE_INT, 0x22c, 0x4}, \
    {"r8", FIELD_OUTPUT_TYPE_INT, 0x230, 0x4}, \
    {"r9", FIELD_OUTPUT_TYPE_INT, 0x234, 0x4}, \
    {"r10", FIELD_OUTPUT_TYPE_INT, 0x238, 0x4}, \
    {"r11", FIELD_OUTPUT_TYPE_INT, 0x23c, 0x4}, \
    {"r12", FIELD_OUTPUT_TYPE_INT, 0x240, 0x4}, \
    {"r13", FIELD_OUTPUT_TYPE_INT, 0x244, 0x4}, \
    {"msp", FIELD_OUTPUT_TYPE_INT, 0x248, 0x4}, \
    {"psp", FIELD_OUTPUT_TYPE_INT, 0x24c, 0x4}, \
    {"lr0_ctrl", FIELD_OUTPUT_TYPE_INT, 0x250, 0x4}, \
    {"lr1", FIELD_OUTPUT_TYPE_INT, 0x254, 0x4}, \
    {"pc", FIELD_OUTPUT_TYPE_INT, 0x258, 0x4}, \
    {"xpsr", FIELD_OUTPUT_TYPE_INT, 0x25c, 0x4}, \
    {"primask", FIELD_OUTPUT_TYPE_INT, 0x260, 0x4}, \
    {"basepri", FIELD_OUTPUT_TYPE_INT, 0x264, 0x4}, \
    {"faultmask", FIELD_OUTPUT_TYPE_INT, 0x268, 0x4}, \
    {"control", FIELD_OUTPUT_TYPE_INT, 0x26c, 0x4}, \
    {"**runtime*******", FIELD_OUTPUT_TYPE_STR, 0x00, 0x8}, \
    {"RT_BBX_MAGIC_NUM", FIELD_OUTPUT_TYPE_INT, 0x7940, 0x4}, \
    {"RT_BBX_SIZE", FIELD_OUTPUT_TYPE_INT, 0x7948, 0x4}, \
    {"TSENSOR_A55", FIELD_OUTPUT_TYPE_INT, 0x7960, 0x1}, \
    {"TSENSOR_PERI", FIELD_OUTPUT_TYPE_INT, 0x7961, 0x1}, \
    {"TSENSOR_AIC0", FIELD_OUTPUT_TYPE_INT, 0x7962, 0x1}, \
    {"TSENSOR_AIC1", FIELD_OUTPUT_TYPE_INT, 0x7963, 0x1}, \
    {"DDR_T_GRADE", FIELD_OUTPUT_TYPE_INT, 0x7964, 0x1}, \
    {"EDP_SCALE_0", FIELD_OUTPUT_TYPE_INT, 0x7965, 0x1}, \
    {"EDP_SCALE_1", FIELD_OUTPUT_TYPE_INT, 0x7966, 0x1}, \
    {"TMP_STATUS", FIELD_OUTPUT_TYPE_INT, 0x7967, 0x1}, \
    {"TMP_CTRL_ST", FIELD_OUTPUT_TYPE_INT, 0x7968, 0x1}, \
    {"AIC_FREQ_ST", FIELD_OUTPUT_TYPE_INT, 0x7969, 0x1}, \
    {"A55_FREQ_ST", FIELD_OUTPUT_TYPE_INT, 0x796A, 0x1}, \
    {"A55_FREQ_ST", FIELD_OUTPUT_TYPE_INT, 0x796B, 0x1}, \
    {"TMP_RST", FIELD_OUTPUT_TYPE_INT, 0x796C, 0x1}, \
    {"TMP_HIGH", FIELD_OUTPUT_TYPE_INT, 0x796D, 0x1}, \
    {"TMP_NOR", FIELD_OUTPUT_TYPE_INT, 0x796E, 0x1}, \
    {"TMP_PERIOD", FIELD_OUTPUT_TYPE_INT, 0x796F, 0x1}, \
    {"T_RST_STATUS", FIELD_OUTPUT_TYPE_INT, 0x797D, 0x1}, \
    {"T_ERR_TSENSOR", FIELD_OUTPUT_TYPE_INT, 0x797E, 0x1}, \
    {"T_ERR_EFUSE", FIELD_OUTPUT_TYPE_INT, 0x797F, 0x1}, \
    {"**NV*******", FIELD_OUTPUT_TYPE_STR, 0x00, 0x8}, \
    {"LPNV_MAGIC",FIELD_OUTPUT_TYPE_INT, 0x7980, 0x4}, \
    {"LP_LPALL_NV",FIELD_OUTPUT_TYPE_INT, 0x7984, 0x1}, \
    {"LP_AVS_NV",FIELD_OUTPUT_TYPE_INT, 0x7985, 0x1}, \
    {"LP_SVFD_NV",FIELD_OUTPUT_TYPE_INT, 0x7986, 0x1}, \
    {"LP_PLLMOD_SEL_NV",FIELD_OUTPUT_TYPE_INT, 0x7987, 0x1}, \
    {"LP_DEEP_SLEEP_NV",FIELD_OUTPUT_TYPE_INT, 0x7988, 0x1}, \
    {"LP_HIMNTN_NV",FIELD_OUTPUT_TYPE_INT, 0x7989, 0x1}, \
    {"LP_LOGBUF_CTRL",FIELD_OUTPUT_TYPE_INT, 0x798A, 0x1}, \
    {"LP_WDT_RST_NV",FIELD_OUTPUT_TYPE_INT, 0x798B, 0x1}, \
    {"LP_RDRLOG_CTRL",FIELD_OUTPUT_TYPE_INT, 0x798C, 0x1}, \
    {"THERMAL_EN_NV", FIELD_OUTPUT_TYPE_INT, 0x798D, 0x1}, \
    {"TMP_HWRST_EN_NV", FIELD_OUTPUT_TYPE_INT, 0x798E, 0x1}, \
    {"TMP_GCTRL_EN_NV", FIELD_OUTPUT_TYPE_INT, 0x798F, 0x1}, \
    {"TMP_GCTRL_SCALE_NV", FIELD_OUTPUT_TYPE_INT, 0x7990, 0x1}, \
    {"TMP_RST_NV", FIELD_OUTPUT_TYPE_INT, 0x7991, 0x1}, \
    {"TMP_HIGH_NV", FIELD_OUTPUT_TYPE_INT, 0x7992, 0x1}, \
    {"TMP_NOR_NV", FIELD_OUTPUT_TYPE_INT, 0x7993, 0x1}, \
    {"TMP_PERIOD_NV", FIELD_OUTPUT_TYPE_INT, 0x7994, 0x1}, \
    {"DDR_ALL_NV", FIELD_OUTPUT_TYPE_INT, 0x7995, 0x1}, \
    {"DDR_THERMAL_NV", FIELD_OUTPUT_TYPE_INT, 0x7996, 0x1}, \
    {"DDR_EXMBIST_NV", FIELD_OUTPUT_TYPE_INT, 0x7997, 0x1}, \
    {"DDR_SWAP_NV", FIELD_OUTPUT_TYPE_INT, 0x7998, 0x1}, \
    {"DDR_IECC_NV", FIELD_OUTPUT_TYPE_INT, 0x7999, 0x1}, \
    {"DDR_PASR_NV", FIELD_OUTPUT_TYPE_INT, 0x799A, 0x1}, \
    {"DDR_UDIS_NV", FIELD_OUTPUT_TYPE_INT, 0x799B, 0x1}, \
    {"DDR_TDIS_NV", FIELD_OUTPUT_TYPE_INT, 0x799C, 0x1}, \
    {"DDR_FREQ_NV", FIELD_OUTPUT_TYPE_INT, 0x799D, 0x1}, \
    {"**DDR_RUNTIME***", FIELD_OUTPUT_TYPE_STR, 0x00, 0x8}, \
    {"DDR_STATUS",      FIELD_OUTPUT_TYPE_INT, 0x79C0, 0x2}, \
    {"INITFREQ",        FIELD_OUTPUT_TYPE_INT, 0x79C2, 0x1}, \
    {"DDR_TMP_PERIOD",  FIELD_OUTPUT_TYPE_INT, 0x79C3, 0x1}, \
    {"DDR_PD_PRD",      FIELD_OUTPUT_TYPE_INT, 0x79C4, 0x2}, \
    {"DDR_ASREF_PRD",   FIELD_OUTPUT_TYPE_INT, 0x79C6, 0x2}, \
    {"DDR_FREQ_LOAD",   FIELD_OUTPUT_TYPE_HEX, 0x79C8, 0x10},\
    {"DDR_MIN",         FIELD_OUTPUT_TYPE_INT, 0x79D8, 0x1}, \
    {"DDR_MAX",         FIELD_OUTPUT_TYPE_INT, 0x79D9, 0x1}, \
    {"DDR_LAST",        FIELD_OUTPUT_TYPE_INT, 0x79DA, 0x1}, \
    {"DDR_CURRENT",     FIELD_OUTPUT_TYPE_INT, 0x79DB, 0x1}, \
    {"DDR_TARGET",      FIELD_OUTPUT_TYPE_INT, 0x79DC, 0x1}, \
    {"DDR_DN_LIMIT",    FIELD_OUTPUT_TYPE_INT, 0x79DD, 0x1}, \
    {"DDR_UP_LIMIT",    FIELD_OUTPUT_TYPE_INT, 0x79DE, 0x1}, \
    {"DDR_PLL",         FIELD_OUTPUT_TYPE_INT, 0x79DF, 0x1}, \
    {"DDR_LAST_PLL",    FIELD_OUTPUT_TYPE_INT, 0x79E0, 0x4}, \
    {"CMD_CNT",         FIELD_OUTPUT_TYPE_HEX, 0x79E4, 0x10},\
    {"DATA_CNT",        FIELD_OUTPUT_TYPE_INT, 0x79F4, 0x4}, \
    {"**efuse*******", FIELD_OUTPUT_TYPE_STR, 0x00, 0x8}, \
    {"TSENSOR_EFUSE", FIELD_OUTPUT_TYPE_INT, 0x7B28, 0x8}, \
}

#define FIELD_DESCRIPTION_LPM3_SRAM  DDR_FIELD_DESCRIPTION_VECTOR(LPM3_SRAM)[]= {\
    {"magic_begin",             FIELD_OUTPUT_TYPE_INT, 0x5000, 0x4}, \
    {"slice_time",              FIELD_OUTPUT_TYPE_INT, 0x5004, 0x4}, \
    {"mod_reason",              FIELD_OUTPUT_TYPE_INT, 0x5008, 0x4}, \
    {"ddr_freq_id",             FIELD_OUTPUT_TYPE_INT, 0x500C, 0x4}, \
    {"uce_exc",                 FIELD_OUTPUT_TYPE_INT, 0x5010, 0x4}, \
    {"reserved0-2",             FIELD_OUTPUT_TYPE_INT, 0x5014, 0x4}, \
    {"reg_save_addr",           FIELD_OUTPUT_TYPE_INT, 0x5020, 0x4}, \
    {"DDRRETENTION",            FIELD_OUTPUT_TYPE_INT, 0x5024, 0x4}, \
    {"DDRRETENTIONCLR",         FIELD_OUTPUT_TYPE_INT, 0x5028, 0x4}, \
    {"DRAMRETENTION",           FIELD_OUTPUT_TYPE_INT, 0x502C, 0x4}, \
    {"DDRC_0_3_RESET",          FIELD_OUTPUT_TYPE_INT, 0x5030, 0x4}, \
    {"DDRC_4_7_RESET",          FIELD_OUTPUT_TYPE_INT, 0x5034, 0x4}, \
    {"DDRC_0_3_PACK_RESET",     FIELD_OUTPUT_TYPE_INT, 0x5038, 0x4}, \
    {"DDRC_4_7_PACK_RESET",     FIELD_OUTPUT_TYPE_INT, 0x503C, 0x4}, \
    {"DDRC_EXMBIST0_REGS_RESET",FIELD_OUTPUT_TYPE_INT, 0x5040, 0x4}, \
    {"DDRC_EXMBIST1_REGS_RESET",FIELD_OUTPUT_TYPE_INT, 0x5044, 0x4}, \
    {"DDRC_0_3_PACK_RESET",     FIELD_OUTPUT_TYPE_INT, 0x5048, 0x4}, \
    {"DDRC_4_7_PACK_RESET",     FIELD_OUTPUT_TYPE_INT, 0x504C, 0x4}, \
    {"SCTRL_DDRC_0_3_AO_RST",   FIELD_OUTPUT_TYPE_INT, 0x5050, 0x4}, \
    {"SCTRL_DDRC_4_7_AO_RST",   FIELD_OUTPUT_TYPE_INT, 0x5054, 0x4}, \
    {"PPLLBYPASS0",             FIELD_OUTPUT_TYPE_INT, 0x5058, 0x4}, \
    {"PPLLBYPASS1",             FIELD_OUTPUT_TYPE_INT, 0x505C, 0x4}, \
    {"PPLL3FCTRL",              FIELD_OUTPUT_TYPE_INT, 0x5060, 0x4}, \
    {"PPLL3FCTRL_FRAC",         FIELD_OUTPUT_TYPE_INT, 0x5064, 0x4}, \
    {"PPLL4FCTRL",              FIELD_OUTPUT_TYPE_INT, 0x5068, 0x4}, \
    {"PPLL4FCTRL_FRAC",         FIELD_OUTPUT_TYPE_INT, 0x506C, 0x4}, \
    {"PPLLOCKSTATUS",           FIELD_OUTPUT_TYPE_INT, 0x5070, 0x4}, \
    {"DDRC_0_3_BYPASS_MODE",    FIELD_OUTPUT_TYPE_INT, 0x5074, 0x4}, \
    {"DDRC_4_7_BYPASS_MODE",    FIELD_OUTPUT_TYPE_INT, 0x5078, 0x4}, \
    {"PLL_PROF_CFG1",           FIELD_OUTPUT_TYPE_INT, 0x507C, 0x4}, \
}

/* TEE module */
#define FIELD_DESCRIPTION_TEE DDR_FIELD_DESCRIPTION_VECTOR(TEE)[]= {\
    {"tee info", FIELD_OUTPUT_TYPE_STR_NL, 0x0, 0x10000}, \
}

/* TF module */
#define FIELD_DESCRIPTION_TF DDR_FIELD_DESCRIPTION_VECTOR(TF)[]= {\
    {"tf info", FIELD_OUTPUT_TYPE_STR_NL, 0x8, 0xFFF8}, \
}

/* DVPP module */
#define FIELD_DESCRIPTION_DVPP DDR_FIELD_DESCRIPTION_VECTOR(DVPP)[]= {\
    {"dvpp info", FIELD_OUTPUT_TYPE_STR_NL, 0x0, 0x10000}, \
}

/* DRIVE module */
#define FIELD_DESCRIPTION_DRIVER DDR_FIELD_DESCRIPTION_VECTOR(DRIVER)[]= {\
    {"driver info", FIELD_OUTPUT_TYPE_STR_NL, 0x0, 0x20000}, \
}

/* TS module */
#define FIELD_DESCRIPTION_TS DDR_FIELD_DESCRIPTION_VECTOR(TS)[]= {\
    {"ts info", FIELD_OUTPUT_TYPE_CHAR, 0x0, 0x30000}, \
}

/* TS module, start */
#define FIELD_DESCRIPTION_TS_START DDR_FIELD_DESCRIPTION_VECTOR(TS_START)[]= {\
    {"ts start info", FIELD_OUTPUT_TYPE_CHAR, 0x0, 0xC800}, \
}

/* AP module, early print */
#define FIELD_DESCRIPTION_AP_EPRINT DDR_FIELD_DESCRIPTION_VECTOR(AP_EPRINT)[]= {\
    {"early print info", FIELD_OUTPUT_TYPE_STR_NL, 0x0, 0x400}, \
}

/* BIOS module */
#define FIELD_DESCRIPTION_BIOS DDR_FIELD_DESCRIPTION_VECTOR(BIOS)[]= {\
    {"bios info", FIELD_OUTPUT_TYPE_STR_NL, 0x0, 0x50000}, \
}

/* BIOS module, sram */
#define FIELD_DESCRIPTION_BIOS_SRAM DDR_FIELD_DESCRIPTION_VECTOR(BIOS_SRAM)[]= {\
    {"LPM3_WAKE_UP_STATUS",             FIELD_OUTPUT_TYPE_INT, 0x0,   0x4 }, \
    {"DEBUG_TIME_POWERUP_DONE",         FIELD_OUTPUT_TYPE_INT, 0x28,  0x4 }, \
    {"DEBUG_TIME_PERSTHIGH_DONE",       FIELD_OUTPUT_TYPE_INT, 0x2C,  0x4 }, \
    {"DEBUG_TIME_PCIEPHY_DONE",         FIELD_OUTPUT_TYPE_INT, 0x30,  0x4 }, \
    {"DEBUG_TIME_PHY_FIRMWARE_DONE",    FIELD_OUTPUT_TYPE_INT, 0x34,  0x4 }, \
    {"DEBUG_TIME_PCIECTRL_DONE",        FIELD_OUTPUT_TYPE_INT, 0x38,  0x4 }, \
    {"DEBUG_TIME_IMG_DONE",             FIELD_OUTPUT_TYPE_INT, 0x3C,  0x4 }, \
    {"DEBUG_TIME_SECURE_DONE",          FIELD_OUTPUT_TYPE_INT, 0x40,  0x4 }, \
    {"DEBUG_VERSION_ADDR",              FIELD_OUTPUT_TYPE_HEX, 0x50,  0x10}, \
    {"XLOADER_RESET_REG",               FIELD_OUTPUT_TYPE_INT, 0x200, 0x4 }, \
    {"XLOADER_KEY_POINT",               FIELD_OUTPUT_TYPE_INT, 0x204, 0x4 }, \
    {"XLOADER_TIME_POWERUP_DONE",       FIELD_OUTPUT_TYPE_INT, 0x228, 0x4 }, \
    {"XLOADER_TIME_PERSTHIGH_DONE",     FIELD_OUTPUT_TYPE_INT, 0x22C, 0x4 }, \
    {"XLOADER_TIME_PCIEPHY_DONE",       FIELD_OUTPUT_TYPE_INT, 0x230, 0x4 }, \
    {"XLOADER_TIME_PHY_FIRMWARE_DONE",  FIELD_OUTPUT_TYPE_INT, 0x234, 0x4 }, \
    {"XLOADER_TIME_PCIECTRL_DONE",      FIELD_OUTPUT_TYPE_INT, 0x238, 0x4 }, \
    {"XLOADER_TIME_PCIE_DETECT_DONE",   FIELD_OUTPUT_TYPE_INT, 0x23C, 0x4 }, \
    {"UEFI_LAST_KEYPOINT",              FIELD_OUTPUT_TYPE_INT, 0x320, 0x4 }, \
    {"SD_LOAD_FILE_STATUS",             FIELD_OUTPUT_TYPE_INT, 0x350, 0x4 }, \
}

#ifdef __cplusplus
}
#endif // __cplusplus
#endif // __BBOX_DDR_FIELD_H_
