/* Copyright (C) 2018. Huawei Technologies Co., Ltd. All rights reserved.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the Apache License Version 2.0.You may not use this file except in compliance with the License.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * Apache License for more details at
 * http://www.apache.org/licenses/LICENSE-2.0
 */
#ifndef DOMI_OMG_COMMON_ATTR_DEFINE_H_
#define DOMI_OMG_COMMON_ATTR_DEFINE_H_

#include <string>
#include "framework/common/fmk_types.h"

namespace domi
{
/**
* 公共属性
*/
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_NAME;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_TYPE;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_WEIGHT_NAME;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_IS_QUANTIZE_FACTOR;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_ALPHA;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_BETA;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_PADMODE;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_PADMODES;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_MODE;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_FILTER;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_BIAS;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_BIAS_TERM;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_HAS_BIAS_VALUE;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_PAD;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_PADS;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_PAD_SIZE;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_PAD_MODE;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_SCALE;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_WINDOWS;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_GLOBAL_POOLING;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_CEIL_MODE;

//extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_WEIGHTS;

//extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_IS_INPUT_CONST;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_STRIDE_SIZE;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_RELU_FLAG;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_ALGO;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_FORMAT;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_FILTER_FORMAT;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_LRN_K;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_LRN_NORM_REGION;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_LRN_LOCAL_SIZE;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_LRN_ALPHA;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_LRN_BETA;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_AXIS;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_BROADCAST;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_OUTPUT_NUM;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_TIDX;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_TPADDINGS;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_IMG_H;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_IMG_W;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NET_H;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NET_W;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_TMULTIPLES;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_MULTIPLES;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_T;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_TSHAPE;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_NAN_OPT;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_AIPP;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string NEW_AIPP_CONV_OP;


static const std::string ATTR_NAME_INPUT_DATATYPE = "input_datatype";
static const std::string ATTR_NAME_OUTPUT_DATATYPE = "output_datatype";

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_MULTISHAPE_BATCHLIST;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_MULTISHAPE_BATCHLIST_SIZE;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_MODEL_BATCH_NUM;


extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_INPUT_FORMAT;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_OUTPUT_FORMAT;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_FRAMEWORK_NODE_DEF;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_FRAMEWORK_OP_DEF;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_FRAMEWORK_FWK_TYPE;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_FRAMEWORK_FUNC_DEF;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_FRAMEWORK_ORIGINAL_TYPE;


extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_INPUT_TENSOR_DESC;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_OUTPUT_TENSOR_DESC;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_INFERRED_FORMAT;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_PRED_PERMUTE_DELETED;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_IGNORE_PRED_FORMAT;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_WEIGHTS;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_BROACAST_REAL_DIM_CNT;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_DIM_ALIGN;

/* to be deleted*/
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_TO_BE_DELETED;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string PERMUTE_RESHAPE_FUSION;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string PERMUTE_RESHAPE_FUSION_CONV_PROPOSAL;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string PERMUTE_RESHAPE_FUSION_CONV_DECODEBBOX;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string PERMUTE_RESHAPE_FUSION_BOX_TYPE_NUM;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string SSD_MBOX_LOC_FUSION;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string SSD_MBOX_CONF_FUSION;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string SSD_MBOX_FUSION_BOX_TYPE_NUM;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string SSD_RESHAPE_SLICE_CONCAT_FUSION;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string SSD_PRIORBOX_CONCAT;


/* _Arg */
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_INDEX;
/* _RetVal */
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string RETVAL_ATTR_NAME_INDEX;
/*Data*/
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string DATA_ATTR_NAME_DATA_TYPE;

/*Send*/
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string SEND_ATTR_EVENT_ID;

/*Recv*/
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string RECV_ATTR_EVENT_ID;

/**
* convolution
*/
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_COEF;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_STRIDE;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_STRIDES;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_DILATION;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_DILATIONS;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string CONV_ATTR_NAME_MODE;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string CONV_ATTR_NAME_ALGO;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string CONV_ATTR_NAME_GROUP;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string CONV_ATTR_NAME_PAD_MODE;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string CONV_ATTR_NAME_PAD;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string CONV_ATTR_NAME_STRIDE;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string CONV_ATTR_NAME_DILATION;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string CONV_ATTR_NAME_NUM_OUTPUT;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string CONV_ATTR_NAME_KERNEL;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string CONV_ATTR_NAME_FILTER;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string CONV_ATTR_NAME_BIAS;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string CONV_ATTR_NAME_RELU_FLAG;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string CONV_ATTR_NAME_ADJ;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string CONV_ATTR_NAME_TARGET_SHAPE;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string CONV_ATTR_NAME_BEFORE_PAD;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string CONV_ATTR_NAME_HAS_BIAS;

/*Pooling*/
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string POOLING_ATTR_MODE;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string POOLING_ATTR_NAN_OPT;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string POOLING_ATTR_PAD_MODE;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string POOLING_ATTR_GLOBAL_POOLING;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string POOLING_ATTR_WINDOW;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string POOLING_ATTR_PAD;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string POOLING_ATTR_STRIDE;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string POOLING_ATTR_CEIL_MODE;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string POOLING_ATTR_DATA_MODE;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string POOLING_ATTR_BEFORE_PAD;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string POOLING_ATTR_NAME_ALGO;


/*Eltwise*/
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ELTWISE_ATTR_MODE;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ELTWISE_ATTR_COEFF;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ELTWISE_ATTR_WEIGHT;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ELTWISE_ATTR_RELU_FLAG;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ELTWISE_ATTR_ALPHA;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ELTWISE_ATTR_BETA;

/*BatchNorm*/
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string BATCHNORM_ATTR_MODE;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string BATCHNORM_ATTR_EPSILON;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string BATCHNORM_ATTR_USE_GLOBAL_STATS  ;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string BATCHNORM_ATTR_MOVING_AVERAGE_FRACTION  ;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string BATCHNORM_ATTR_ESTIMATED_MEAN;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string BATCHNORM_ATTR_ESTIMATED_VARIANCE ;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string BATCHNORM_ATTR_SCALE;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string BATCHNORM_ATTR_BIAS;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string BATCHNORM_ATTR_DATA_FORMAT;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string BATCHNORM_ATTR_IS_TRAINING;

/*Scale*/
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string SCALE_ATTR_SCALE;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string SCALE_ATTR_BIAS;

/*FullConnection*/
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string FULL_CONNECTION_ATTR_FILTER;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string FULL_CONNECTION_ATTR_BIAS;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string FULL_CONNECTION_ATTR_NUM_OUTPUT;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string FULL_CONNECTION_ATTR_RELU_FLAG;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string FULL_ATTR_NAME_ALGO;


/*SoftmaxOpParams*/
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string SOFTMAX_ATTR_ALGO;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string SOFTMAX_ATTR_MODE;

/*Activation*/
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ACTIVATION_ATTR_MODE;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ACTIVATION_ATTR_COEF;

/* Concat */
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string CONCAT_ATTR_NAME_AXIS;

/* Const */
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string CONST_ATTR_NAME_DATA_TRANSTYPE;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string CONST_ATTR_NAME_OUTPUT_FORMAT;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string CONST_ATTR_NAME_OUTPUT_TYPE;

 /* roipooling */
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ROIPOOLING_ATTR_NAME_POOLED_H;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ROIPOOLING_ATTR_NAME_POOLED_W;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ROIPOOLING_ATTR_NAME_SPATIAL_SCALE;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ROIPOOLING_ATTR_NAME_RIO_POOLING_MODE;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ROIPOOLING_ATTR_NAME_POOLING_MODE;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ROIPOOLING_ATTR_NAME_SAMPLING_RATIO;

/* DetectionOutput */
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string DETECTIONOUTPUT_ATTR_NUM_CLASSES;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string DETECTIONOUTPUT_ATTR_NMS_THRESHOLD;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string DETECTIONOUTPUT_ATTR_TOP_K;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string DETECTIONOUTPUT_ATTR_CONFIDENCE_THRESHOLD;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string DETECTIONOUTPUT_ATTR_IMG_H;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string DETECTIONOUTPUT_ATTR_IMG_W;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string DETECTIONOUTPUT_ATTR_BATCH_SIZE;
/* Ssd DetectionOutput */
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string DETECTIONOUTPUT_ATTR_ETA;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string DETECTIONOUTPUT_ATTR_SHARED_LOCATION;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string DETECTIONOUTPUT_ATTR_BACKGROUND_LABEL_ID;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string DETECTIONOUTPUT_ATTR_CODE_TYPE;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string DETECTIONOUTPUT_ATTR_VARIANCE_ENCODED_IN_TARGET;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string DETECTIONOUTPUT_ATTR_KEEP_TOP_K;
/* yolo DetectionOutput */
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string DETECTIONOUTPUT_ATTR_ClASSES;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string DETECTIONOUTPUT_ATTR_BIASES;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string DETECTIONOUTPUT_ATTR_RELATIVE;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string DETECTIONOUTPUT_ATTR_OBJECTNESS_THRESHOLD;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string DETECTIONOUTPUT_ATTR_CLASS_THRESHOLD;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string DETECTIONOUTPUT_ATTR_POST_TOP_K;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string DETECTIONOUTPUT_ATTR_IOU_THRESHOLD_DECAY;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string DETECTIONOUTPUT_ATTR_COOR_SCALE_FACTOR;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string DETECTIONOUTPUT_ATTR_YOLO_VERSION;

/* DetectionPostprocess */
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string POSTPROCESS_ATTR_NAME_CLS_NUM;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string POSTPROCESS_ATTR_NAME_CONF_THRESH;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string POSTPROCESS_ATTR_NAME_NMS_THRESH;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string POSTPROCESS_ATTR_POST_NMS_TOPN;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string POSTPROCESS_ATTR_NAME_BBOX_REG_WEIGHT;

/* Spatialtransfrom */
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string SPTIALTF_ATTR_NAME_OUTPUT_H;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string SPTIALTF_ATTR_NAME_OUTPUT_W;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string SPTIALTF_ATTR_NAME_BORDER_VALUE;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string SPTIALTF_ATTR_NAME_AFFINE_TRANSFORM;

/* Proposal */
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string PROPOSAL_ATTR_NAME_FEAT_STRIDE;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string PROPOSAL_ATTR_NAME_BASE_SIZE;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string PROPOSAL_ATTR_NAME_MIN_SIZE;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string PROPOSAL_ATTR_NAME_RATIO;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string PROPOSAL_ATTR_NAME_SCALE;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string PROPOSAL_ATTR_NAME_PRE_NMS_TOPN;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string PROPOSAL_ATTR_NAME_POST_NMS_TOPN;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string PROPOSAL_ATTR_NAME_NMS_THRESH;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string PROPOSAL_ATTR_NAME_TOP_SIZE;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string PROPOSAL_ATTR_IMG_H;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string PROPOSAL_ATTR_IMG_W;
/* Softmax */
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string SOFTMAX_ATTR_AXIS;

/* Permute */
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string PERMUTE_ATTR_ORDER;

/*SSD Normalize*/
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string SSDNORMALIZE_ATTR_ACCROSS_SPATIAL;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string SSDNORMALIZE_ATTR_CHANNEL_SHARED;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string SSDNORMALIZE_ATTR_EPS;

/* Flatten */
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string FLATTEN_ATTR_AXIS;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string FLATTEN_ATTR_END_AXIS;

/* SsdPRIORBOX */
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string SSD_PRIOR_BOX_ATTR_FLIP;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string SSD_PRIOR_BOX_ATTR_CLIP;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string SSD_PRIOR_BOX_ATTR_IMG_H;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string SSD_PRIOR_BOX_ATTR_IMG_W;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string SSD_PRIOR_BOX_ATTR_STEP_H;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string SSD_PRIOR_BOX_ATTR_STEP_W;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string SSD_PRIOR_BOX_ATTR_OFFSET;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string SSD_PRIOR_BOX_ATTR_MIN_SIZE;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string SSD_PRIOR_BOX_ATTR_MAX_SIZE;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string SSD_PRIOR_BOX_ATTR_MIN_SIZE_NUM;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string SSD_PRIOR_BOX_ATTR_MAX_SIZE_NUM;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string SSD_PRIOR_BOX_ATTR_ASPECT_RATIO;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string SSD_PRIOR_BOX_ATTR_ASPECT_RATIO_NUM;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string SSD_PRIOR_BOX_ATTR_VARIANCE;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string SSD_PRIOR_BOX_ATTR_VARIANCE_NUM;

/* PRelu */
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string PRELU_ATTR_CHANNEL_SHARED;

/*psroi pooling*/
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string PSROIPOOLING_ATTR_SPATIAL_SCALE;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string PSROIPOOLING_ATTR_OUTPUT_DIM;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string PSROIPOOLING_ATTR_GROUP_SIZE;

/* power */
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string POWER_ATTR_NAME_POWER;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string POWER_ATTR_NAME_SCALE;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string POWER_ATTR_NAME_SHIFT;

	/* log */
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string LOG_ATTR_NAME_SCALE;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string LOG_ATTR_NAME_SHIFT;
	extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string LOG_ATTR_NAME_BASE;

/*pack*/
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string PACK_ATTR_NAME_NUM;

/*unpack*/
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string UNPACK_ATTR_NAME_NUM;
/*gathernd*/
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string GATHERND_ATTR_NAME_TINDICES;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string GATHERND_ATTR_NAME_TPARAMS;

 /*argmax*/
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ARGMAX_ATTR_NAME_TOPK;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ARGMAX_ATTR_NAME_OUTMAX;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ARGMAX_ATTR_NAME_AXIS;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ARGMAX_ATTR_NAME_AXISTYPE;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ARGMAX_ATTR_NAME_KEEPDIMS;

/*upsample*/
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string UPSAMPLE_ATTR_NAME_SCALE_H;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string UPSAMPLE_ATTR_NAME_SCALE_W;

/* relu */
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_NEGATIVE_SLOPE;

/* FreeSpaceExtract */
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string FREESPACEEXTRACT_ATTR_NAME_ORG_HEIGHT;

/* split */
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string SPLIT_ATTR_NAME_SLICE_POINT;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string SPLIT_ATTR_NAME_SIZE_SPLIT;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string SPLIT_ATTR_NAME_NUM_SPLIT;

/* Tvm */
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string TVM_ATTR_NAME_MAGIC;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string TVM_ATTR_NAME_BLOCKDIM;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string TVM_ATTR_NAME_METADATA;

/*squeeze*/
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string SQUEEZE_ATTR_AXIS;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string SQUEEZE_ATTR_DIMS;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string SQUEEZE_OP_NAME;

/*stride slice*/
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string STRIDE_SLICE_ATTR_BEGIN_MASK;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string STRIDE_SLICE_ATTR_END_MASK;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string STRIDE_SLICE_ATTR_ELLIPSIS_MASK;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string STRIDE_SLICE_ATTR_NEW_AXIS_MASK;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string STRIDE_SLICE_ATTR_SHRINK_AXIS_MASK;

/*slice*/
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string SLICE_ATTR_NAME_BEGINS;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string SLICE_ATTR_NAME_SIZES;

/*roialign*/
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ROIALIGN_ATTR_SPATIAL_SCALE;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ROIALIGN_ATTR_SAMPLING_RATIO;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ROIALIGN_ATTR_NAME_POOLED_H;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ROIALIGN_ATTR_NAME_POOLED_W;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ROIALIGN_ATTR_NAME_TF;

/*generate_rpn_proposal*/
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string GENERATE_RPN_PROPOSAL_ATTR_PRE_NMS_TOPK;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string GENERATE_RPN_PROPOSAL_ATTR_POST_NMS_TOPK;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string GENERATE_RPN_PROPOSAL_ATTR_RPN_MINI_SIZE;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string GENERATE_RPN_PROPOSAL_ATTR_RPN_PROPOSAL_NMS_THRESH   ;

/*decode_bbox*/
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string DECODE_BBOX_ATTR_DECODECLIP;

/* Cast */
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string CAST_ATTR_DSTT;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string CAST_ATTR_SRCT;

/* fastrcnnn predications*/
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string FASTRCNN_PREDICTIONS_ATTR_TOPK;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string FASTRCNN_PREDICTIONS_ATTR_SCORE_THRESHOLD;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string FASTRCNN_PREDICTIONS_ATTR_NMS_THRESHOLD;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string FASTRCNN_PREDICTIONS_ATTR_NUM_CLASSES;

/* REORG*/
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string REORG_ATTR_STRIDE;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string REORG_ATTR_REVERSE;

/* MERGE*/
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string MERGE_DEAD_INDEX;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string MERGE_PRENODE_FLAG;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string TO_BE_OUTPUT;
static const std::string NOT_NET_OUTPUT = "not_net_output";

/*Concatv2*/
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string CONCAT_V2_ATTR_TIDX;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string CONCAT_V2_ATTR_N;
  /* SUM*/
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string SUM_ATTR_TIDX;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string SUM_ATTR_AXIS;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string SUM_ATTR_KEEP_DIMS;

/*ResizeBilinear*/
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string RESIZE_BILINEAR_ATTR_MODE;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string RESIZE_BILINEAR_ATTR_ALIGN_CORNERS;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string RESIZE_BILINEAR_ATTR_HEIGHT;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string RESIZE_BILINEAR_ATTR_WIDTH;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string RESIZE_BILINEAR_ATTR_ZOOM_FACTOR;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string RESIZE_BILINEAR_ATTR_SHRINK_FACTOR;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string RESIZE_BILINEAR_ATTR_PAD_BEGIN;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string RESIZE_BILINEAR_ATTR_PAD_END;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string RESIZE_BILINEAR_ATTR_ALPHA;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string RESIZE_BILINEAR_ATTR_BETA ;

/*RetinaNet*/
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string RETINANET_FILTER_BACKGROUND_TRUE;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string RETINANET_ANCHOR_FUSION;

/*MatMul*/
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string MATMUL_TRANSPOSE_X;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string MATMUL_TRANSPOSE_W;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string MATMUL_HAS_BIAS;

/*Flatten*/
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string FLATTEN_START_AXIS;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string FLATTEN_END_AXIS;

/*reshape*/
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string RESHAPE_ATTR_AXIS;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string RESHAPE_ATTR_NUM_AXES;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string RESHAPE_ATTR_FORMAT;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string RESHAPE_ATTR_SHAPE;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string RESHAPE_ATTR_ALPHA;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string RESHAPE_ATTR_BETA;

/*frameoworkop*/
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string TENSORFLOW_IN_DATATYPE;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string TENSORFLOW_OUT_DATATYPE;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_OUT_N;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_OUT_C;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_OUT_H;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_OUT_W;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_PAD_DEPTH_CONV;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_PAD_CONV;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_BEFORE_PAD;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ANN_MEAN_KEEPDIMS;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string PAD_ATTR_PADDINGDS;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string PAD_ATTR_CONSTANT_VALUE;

/*ConvGradFilter*/
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string CONV_GRAD_FILTER_OUTPUT_SHAPE;
/*ConvGradInput*/
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string CONV_GRAD_INPUT_OUTPUT_SHAPE;

/*Rnn*/
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string RNN_TENSORFLOW;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string RNN_MODE_STATIC;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string MUTI_RNN;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string CELL_MODE;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string CNN_RNN;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string LSTM_CELL;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string GRU_CELL;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string RNN_HT;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string RNN_XT_HT;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string RNN_BATCH_SIZE;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string LSTM_CELL_CLIP;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string LSTM_PROJ_CLIP;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string LSTM_ACTIVATE;

/*Upsample*/
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string UPSAMPLE_ATTR_NAME_SCALE;

/*PadV2*/
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string PADV2_ATTR_NAME_MODE;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string PADV2_ATTR_NAME_PADS;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string PADV2_ATTR_NAME_T;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string PADV2_ATTR_NAME_PAD_FORMAT;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string PADV2_ATTR_NAME_CONST_VALUE;

/*MirrorPad*/
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string MIRRORPAD_ATTR_NAME_MODE;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string MIRRORPAD_ATTR_NAME_PADS;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string MIRRORPAD_ATTR_NAME_PAD_FORMAT;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string MIRRORPAD_ATTR_NAME_CONST_VALUE;

/* filler */
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string FILLER_TYPE;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string FILLER_VALUE;

/*shufflechannel*/
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string SHUFFLE_CHANNEL_GROUP;

/*TopKV2*/
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string TOPKV2_ATTR_K;

/*Calibaration*/
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string STRIDE_H_INDEX;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string STRIDE_W_INDEX;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string PAD_TOP_INDEX;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string PAD_BOTTOM_INDEX;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string PAD_RIGHT_INDEX;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string PAD_LEFT_INDEX;
//extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string QUANTIZE_ALGO_ATTR;
//extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string SCALE_TYPE_ATTR;

//extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string QUANTIZE_SCALE_MODE;
//extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string QUANTIZE_SCALE_VALUE;
//extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string QUANTIZE_SCALE_OFFSET;
//extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string QUANTIZE_OFFSET_DATA_VALUE;
//extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string QUANTIZE_OFFSET_DATA_OFFSET;
//extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string QUANTIZE_OFFSET_WEIGHT_VALUE;
//extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string QUANTIZE_OFFSET_WEIGHT_OFFSET;
//extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string QUANTIZE_OFFSET_PAD_VALUE;
//extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string QUANTIZE_OFFSET_PAD_OFFSET;
//
//extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string DEQUANTIZE_SCALE_MODE;
//extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string DEQUANTIZE_SCALE_VALUE;
//extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string DEQUANTIZE_SCALE_OFFSET;
//extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string DEQUANTIZE_OFFSET_DATA_TYPE;
//extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string DEQUANTIZE_OFFSET_DATA_OFFSET;
//extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string DEQUANTIZE_OFFSET_WEIGHT_VALUE;
//extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string DEQUANTIZE_OFFSET_WEIGHT_OFFSET;
//extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string DEQUANTIZE_OFFSET_PAD_VALUE;
//extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string DEQUANTIZE_OFFSET_PAD_OFFSET;

//extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string REQUANTIZE_SCALE_MODE;
//extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string REQUANTIZE_SCALE_VALUE;
//extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string REQUANTIZE_SCALE_OFFSET;
//extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string REQUANTIZE_OFFSET_DATA_VALUE;
//extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string REQUANTIZE_OFFSET_DATA_OFFSET;
//extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string REQUANTIZE_OFFSET_WEIGHT_VALUE;
//extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string REQUANTIZE_OFFSET_WEIGHT_OFFSET;
//extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string REQUANTIZE_OFFSET_PAD_VALUE;
//extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string REQUANTIZE_OFFSET_PAD_OFFSET;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_IS_CONST;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_GROUP;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_DILATION_SIZE;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_EPSILON;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_POOLING_MODE;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_CLASS_NUM;
/**
* model
*/
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_MODEL_TARGET_TYPE;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_MODEL_STREAM_NUM;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_MODEL_EVENT_NUM;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_MODEL_MEMORY_SIZE;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_MODEL_WEIGHT_SIZE;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_MODEL_TASK_GEN_BASE_ADDR;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_MODEL_TASK_GEN_WEIGHT_ADDR;

/**
* 公共属性
*/
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_IMPLY_TYPE;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_BYTE_SIZE;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_FUSION_INFERENCE_ID;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_FUSION_OPDEF;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_FUSION_SCOPE;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_OPATTR;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_RELUFLAG;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_SEQLEN_INDEX;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_X_INDEX;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_CONT_INDEX;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string ATTR_NAME_XSTATIC_INDEX;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string TARGET_TYPE_MINI ;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string TARGET_TYPE_TINY ;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string TARGET_TYPE_LITE ;


/*l2_normalize*/
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string L2_NORMALIZE_ATTR_AXIS;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string L2_NORMALIZE_ATTR_EPS ;

extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string POOL_PARAMA_ATTR_WINDOW;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string POOL_PARAMA_ATTR_CEIL_MODE;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string POOL_PARAMA_ATTR_DATA_MODE;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string POOL_PARAMA_ATTR_GLOBAL_POOLING;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string POOL_PARAMA_ATTR_NAN_OP;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string POOL_PARAMA_ATTR_PAD_MOD;
/*HCOM*/
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string HCOM_ATTR_ROOT_RANK;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string HCOM_ATTR_REDUCE_TYPE;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string HCOM_ATTR_CURRENT_INDEX;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string HCOM_ATTR_RANK_SIZE;

/*SpaceToDepth/DepthToSpace*/
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string TENSORFLOW_ATTR_NAME_BLOCK_SIZE;

/*SparseSoftmaxCrossEntropyWithLogits*/
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string SPARSE_SOFT_MAX_ATTR_TLABLES;

/*MaxPoolGradWithArgmax*/
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string MAX_POOL_GRAD_OUTPUT_SHAPE;

/*Pad*/
extern const std::string ATTR_PAD_FORMAT;

/*Varible*/
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string VAR_ATTR_FORMAT;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string VAR_ATTR_NAME;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string VAR_ATTR_FRACTALZ_FORMAT;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string VAR_ATTR_4D_FORMAT;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string VAR_ATTR_5D_FORMAT;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string VAR_ATTR_DATA_TYPE;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string VAR_ATTR_VAR_IN_NAME;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string VAR_ATTR_VAR_IN_INDEX;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string VAR_ATTR_VAR_OUT_INDEX;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string VAR_ATTR_SHAPE;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string HALF_VAR_NAME_END;

/* space2bacth batch2space */
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string BATCH_SPACE_ATTR_BLOCK;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string BATCH_SPACE_ATTR_PADDING;
/*depth_to_space space_to_depth*/
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string DEPTH_SPACE_ATTR_BLOCK_SIZE;
/*FakeQuantWithMinMaxVars*/
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string FakeQuantWithMinMaxVars_ATTR_MAX;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string FakeQuantWithMinMaxVars_ATTR_MIN ;
/*mobilenet_ssd_conv_fusion*/
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string SSD_BOXPREDICTOR_BOXES_FUSION;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string SSD_BOXPREDICTOR_SCORES_FUSION ;
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string SSD_BOXPREDICTOR_FUSION_BOX_TYPE_NUM;

/*lsh project*/
extern FMK_FUNC_HOST_VISIBILITY FMK_FUNC_DEV_VISIBILITY  const std::string  LSH_PROJ_TYPE;
}

#endif
