TEMPLATE = app
CONFIG += console c++11
CONFIG -= app_bundle
CONFIG -= qt

SOURCES += \
    Common/DvppJpegEncode/DvppJpegEncode.cpp \
    DstEngine/DstEngine.cpp \
    JpegEncode/JpegEncode.cpp \
    ObjectClassification/ObjectClassification.cpp \
    SSDDetection/SSDDetection.cpp \
    StreamPuller/StreamPuller.cpp \
    VDecEngine/VDecEngine.cpp \
    Common/DvppJpegEncode/DvppJpegEncode.cpp \
    main.cpp \
    BicycleDetectionModule/BicycleDetection.cpp \
    DataTypes/AreaInfo.cpp \
    DataTypes/BaseClass.cpp \
    DataTypes/BicycleObjectsBuffer.cpp \
    DataTypes/BoardParams.cpp \
    DataTypes/CalibrationInfo.cpp \
    DataTypes/CalibrationMethod.cpp \
    DataTypes/DataBaseContainer.cpp \
    DataTypes/DatabaseController.cpp \
    DataTypes/DataContainer.cpp \
    DataTypes/DetectionParam.cpp \
    DataTypes/Device.cpp \
    DataTypes/DeviceDatabase.cpp \
    DataTypes/DeviceInfo.cpp \
    DataTypes/EventItem.cpp \
    DataTypes/MyString.cpp \
    DataTypes/ObjectBicycle.cpp \
    DataTypes/SystemDatabase.cpp \
    DataTypes/SystemInfo.cpp \
    DataTypes/Toolset.cpp \
    Sqlite3Manager/Backup.cpp \
    Sqlite3Manager/Column.cpp \
    Sqlite3Manager/Database.cpp \
    Sqlite3Manager/Exception.cpp \
    Sqlite3Manager/Statement.cpp \
    Sqlite3Manager/Transaction.cpp \
    Sqlite3Manager/sqlite3.c \
    BicycleDetectionModule/BicycleDetection.cpp \
    ParamManager/AbstractParameter.cpp \
    ParamManager/LaneAreaParameter.cpp \
    ParamManager/ParameterManager.cpp \
    Sqlite3Manager/Backup.cpp \
    Sqlite3Manager/Column.cpp \
    Sqlite3Manager/Database.cpp \
    Sqlite3Manager/Exception.cpp \
    Sqlite3Manager/Statement.cpp \
    Sqlite3Manager/Transaction.cpp \
    Sqlite3Manager/sqlite3.c \
    GoAhead/WebServer.cpp \
    GoAhead/action.c \
    GoAhead/alloc.c \
    GoAhead/auth.c \
    GoAhead/cgi.c \
    GoAhead/crypt.c \
    GoAhead/file.c \
    GoAhead/fs.c \
    GoAhead/goahead.c \
    GoAhead/http.c \
    GoAhead/js.c \
    GoAhead/jst.c \
    GoAhead/options.c \
    GoAhead/osdep.c \
    GoAhead/rom.c \
    GoAhead/route.c \
    GoAhead/runtime.c \
    GoAhead/socket.c \
    GoAhead/time.c \
    GoAhead/upload.c \
    GoAhead/webapi.cpp \
    graphmanager.cpp \
    GraphManager/graphmanager.cpp \
    HttpService/HttpService.cpp \
    PostSsdResultsEngine/PostSsdResultsEngine.cpp \
    sdk-ezdvpp/dvpp_process.cpp \
    sdk-ezdvpp/dvpp_utils.cpp \
    video_decode/video_decode.cpp \
    StreamDemux/StreamDemux.cpp \
    object_detection/object_detection.cpp

INCLUDEPATH+=$$PWD/Common
INCLUDEPATH+=$$PWD/DataTypes
INCLUDEPATH+=$$PWD/
INCLUDEPATH+=$$PWD/GraphManager
INCLUDEPATH+=$$PWD/BicycleDetectionModule
INCLUDEPATH+=$$PWD/Common/DvppJpegEncode
INCLUDEPATH+=$$PWD/Sqlite3Manager/SQLiteCpp
INCLUDEPATH+=$$PWD/Sqlite3Manager/
INCLUDEPATH+=$$PWD/include/
INCLUDEPATH+=$$PWD/include/curl
INCLUDEPATH+=$$PWD/include/rapidjson
INCLUDEPATH+=$$PWD/include/third_party/
INCLUDEPATH+=$$PWD/include/libc_sec/include
INCLUDEPATH+=$$PWD/include/inc
INCLUDEPATH+=$$PWD/include/inc/cce
INCLUDEPATH+=$$PWD/include/inc/custom/common/
INCLUDEPATH+=$$PWD/include/inc/custom/common/op
INCLUDEPATH+=$$PWD/include/inc/custom/common/op_def
INCLUDEPATH+=$$PWD/include/inc/custom/omg
INCLUDEPATH+=$$PWD/include/inc/custom/omg/graph
INCLUDEPATH+=$$PWD/include/inc/custom/omg/model
INCLUDEPATH+=$$PWD/include/inc/custom/omg/model/op_builder
INCLUDEPATH+=$$PWD/include/inc/custom/omg/parser
INCLUDEPATH+=$$PWD/include/inc/custom/omg/parser/caffe
INCLUDEPATH+=$$PWD/include/inc/custom/omg/parser/tensorflow
INCLUDEPATH+=$$PWD/include/inc/custom/proto
INCLUDEPATH+=$$PWD/include/inc/custom/proto/caffe
INCLUDEPATH+=$$PWD/include/inc/custom/proto/tensorflow
INCLUDEPATH+=$$PWD/include/inc/custom/toolchain
INCLUDEPATH+=$$PWD/include/inc/driver
INCLUDEPATH+=$$PWD/include/inc/dvpp
INCLUDEPATH+=$$PWD/include/inc/hiaiengine/proto
INCLUDEPATH+=$$PWD/include/inc/mmpa/sub_inc
INCLUDEPATH+=$$PWD/include/inc/proto
INCLUDEPATH+=$$PWD/include/inc/tensor_engine
INCLUDEPATH+=$$PWD/include/third_party/glog
INCLUDEPATH+=$$PWD/include/third_party/glog/include
INCLUDEPATH+=$$PWD/include/third_party/gflags
INCLUDEPATH+=$$PWD/include/third_party/gflags/include
INCLUDEPATH+=$$PWD/include/third_party/opencv
INCLUDEPATH+=$$PWD/include/third_party/opencv/include
INCLUDEPATH+=$$PWD/include/third_party/opencv/include/opencv2
INCLUDEPATH+=$$PWD/include/third_party/opencv/include/opencv2/stitching
INCLUDEPATH+=$$PWD/include/third_party/opencv/include/opencv2/core
INCLUDEPATH+=$$PWD/include/third_party/opencv/include/opencv2/core/opencl
INCLUDEPATH+=$$PWD/include/third_party/opencv/include/opencv2/core/opencl/runtime
INCLUDEPATH+=$$PWD/include/third_party/opencv/include/opencv2/core/cuda
INCLUDEPATH+=$$PWD/include/third_party/opencv/include/opencv2/features2d
INCLUDEPATH+=$$PWD/include/third_party/opencv/include/opencv2/imgproc
INCLUDEPATH+=$$PWD/include/third_party/cereal
INCLUDEPATH+=$$PWD/include/third_party/cereal/include
INCLUDEPATH+=$$PWD/include/third_party/cereal/include/cereal
INCLUDEPATH+=$$PWD/include/third_party/cereal/include/cereal/types
INCLUDEPATH+=$$PWD/include/third_party/cereal/include/cereal/external
INCLUDEPATH+=$$PWD/include/third_party/cereal/include/cereal/external/rapidjson
INCLUDEPATH+=$$PWD/include/third_party/protobuf
INCLUDEPATH+=$$PWD/include/third_party/protobuf/include
INCLUDEPATH+=$$PWD/include/third_party/protobuf/include/google
INCLUDEPATH+=$$PWD/include/third_party/protobuf/include/google/protobuf
INCLUDEPATH+=$$PWD/include/third_party/protobuf/include/google/protobuf/compiler

HEADERS += \
    Common/DvppJpegEncode/DvppJpegEncode.h \
    DstEngine/DstEngine.h \
    JpegEncode/JpegEncode.h \
    ObjectClassification/ObjectClassification.h \
    SSDDetection/SSDDetection.h \
    StreamPuller/StreamPuller.h \
    VDecEngine/VDecEngine.h \
    Common/DvppJpegEncode/DvppJpegEncode.h \
    Common/AppCommon.h \
    Common/Common.h \
    Common/common_data_type.h \
    Common/DataRecv.h \
    Common/dvpp_utils.h \
    Common/DynamicGraph.h \
    Common/engine_tools.h \
    Common/error_code.h \
    Common/RawDataBufferHigh.h \
    Common/stream_data.h \
    Common/TransSear.h \
    Common/utils_common.h \
    include/inc/cce/blas_device_api.h \
    include/inc/cce/blas_struct.h \
    include/inc/cce/customize.h \
    include/inc/custom/common/op/attr_define.h \
    include/inc/custom/common/op/attr_value_util.h \
    include/inc/custom/common/op_def/ir_pb_converter.h \
    include/inc/custom/common/op_def/op_schema.h \
    include/inc/custom/common/op_def/operator.h \
    include/inc/custom/common/aicpu_op.h \
    include/inc/custom/common/fmk_error_codes.h \
    include/inc/custom/common/fmk_types.h \
    include/inc/custom/common/op_types.h \
    include/inc/custom/common/tuple.h \
    include/inc/custom/common/types.h \
    include/inc/custom/omg/graph/graph.h \
    include/inc/custom/omg/model/op_builder/op_builder.h \
    include/inc/custom/omg/model/op_builder/tvm_op_builder.h \
    include/inc/custom/omg/parser/caffe/caffe_op_parser.h \
    include/inc/custom/omg/parser/caffe/caffe_parser_register.h \
    include/inc/custom/omg/parser/caffe/caffe_tvm_op_parser.h \
    include/inc/custom/omg/parser/tensorflow/tensorflow_fusion_op_parser.h \
    include/inc/custom/omg/parser/tensorflow/tensorflow_op_parser.h \
    include/inc/custom/omg/parser/tensorflow/tensorflow_util.h \
    include/inc/custom/omg/parser/model_parser.h \
    include/inc/custom/omg/parser/op_parser.h \
    include/inc/custom/omg/parser/op_parser_factory.h \
    include/inc/custom/omg/parser/weights_parser.h \
    include/inc/custom/omg/omg_types.h \
    include/inc/custom/omg/register.h \
    include/inc/custom/toolchain/bbox_ddr_data.h \
    include/inc/custom/toolchain/ide_daemon_api.h \
    include/inc/custom/toolchain/ide_tlv.h \
    include/inc/custom/toolchain/profiler_client.h \
    include/inc/custom/toolchain/slog.h \
    include/inc/custom/custom_op.h \
    include/inc/driver/peripheral_api.h \
    include/inc/dvpp/Base.h \
    include/inc/dvpp/CmdList.h \
    include/inc/dvpp/Dvpp.h \
    include/inc/dvpp/dvpp_config.h \
    include/inc/dvpp/export_macro.h \
    include/inc/dvpp/ExportMacro.h \
    include/inc/dvpp/icmdlistapi.h \
    include/inc/dvpp/idvppapi.h \
    include/inc/dvpp/idvppcapability.h \
    include/inc/dvpp/ijpegdapi.h \
    include/inc/dvpp/ijpegeapi.h \
    include/inc/dvpp/ivdecapi.h \
    include/inc/dvpp/ivencapi.h \
    include/inc/dvpp/ivpcapi.h \
    include/inc/dvpp/Jpeg.h \
    include/inc/dvpp/Png.h \
    include/inc/dvpp/Vdec.h \
    include/inc/dvpp/vdec_hiai.h \
    include/inc/dvpp/Venc.h \
    include/inc/dvpp/Vpc.h \
    include/inc/framework/common/fmk_error_codes.h \
    include/inc/framework/common/fmk_types.h \
    include/inc/framework/common/op_types.h \
    include/inc/framework/common/types.h \
    include/inc/framework/omg/hiai_ir_build.h \
    include/inc/framework/omg/omg_types.h \
    include/inc/framework/omg/register.h \
    include/inc/graph/debug/ge_error_codes.h \
    include/inc/graph/detail/attributes_holder.h \
    include/inc/graph/op/all_ops.h \
    include/inc/graph/op/array_defs.h \
    include/inc/graph/op/const_defs.h \
    include/inc/graph/op/detection_defs.h \
    include/inc/graph/op/math_defs.h \
    include/inc/graph/op/nn_defs.h \
    include/inc/graph/attr_value.h \
    include/inc/graph/buffer.h \
    include/inc/graph/graph.h \
    include/inc/graph/model.h \
    include/inc/graph/operator.h \
    include/inc/graph/operator_reg.h \
    include/inc/graph/tensor.h \
    include/inc/graph/types.h \
    include/inc/graph/usr_types.h \
    include/inc/hiaiengine/ai_alg_api.h \
    include/inc/hiaiengine/ai_client.h \
    include/inc/hiaiengine/ai_memory.h \
    include/inc/hiaiengine/ai_model_manager.h \
    include/inc/hiaiengine/ai_model_parser.h \
    include/inc/hiaiengine/ai_nn_node.h \
    include/inc/hiaiengine/ai_nn_tensor_list.h \
    include/inc/hiaiengine/ai_tensor.h \
    include/inc/hiaiengine/ai_types.h \
    include/inc/hiaiengine/api.h \
    include/inc/hiaiengine/c_api.h \
    include/inc/hiaiengine/c_graph.h \
    include/inc/hiaiengine/data_recv_interface.h \
    include/inc/hiaiengine/data_type.h \
    include/inc/hiaiengine/data_type_reg.h \
    include/inc/hiaiengine/engine.h \
    include/inc/hiaiengine/graph.h \
    include/inc/hiaiengine/init.h \
    include/inc/hiaiengine/log.h \
    include/inc/hiaiengine/multitype_queue.h \
    include/inc/hiaiengine/power_state.h \
    include/inc/hiaiengine/profile.h \
    include/inc/hiaiengine/status.h \
    include/inc/mmpa/sub_inc/mmpa_linux.h \
    include/inc/mmpa/sub_inc/mmpa_typedef_linux.h \
    include/inc/mmpa/sub_inc/mmpa_typedef_win.h \
    include/inc/mmpa/sub_inc/mmpa_win.h \
    include/inc/mmpa/mmpa_api.h \
    include/inc/proto/ai_types.pb.h \
    include/inc/proto/graph_config.pb.h \
    include/inc/tensor_engine/cce_aicpu_3rd_party.h \
    include/libc_sec/include/securec.h \
    include/libc_sec/include/securectype.h \
    include/third_party/cereal/include/cereal/archives/adapters.hpp \
    include/third_party/cereal/include/cereal/archives/binary.hpp \
    include/third_party/cereal/include/cereal/archives/json.hpp \
    include/third_party/cereal/include/cereal/archives/portable_binary.hpp \
    include/third_party/cereal/include/cereal/archives/xml.hpp \
    include/third_party/cereal/include/cereal/details/helpers.hpp \
    include/third_party/cereal/include/cereal/details/polymorphic_impl.hpp \
    include/third_party/cereal/include/cereal/details/polymorphic_impl_fwd.hpp \
    include/third_party/cereal/include/cereal/details/static_object.hpp \
    include/third_party/cereal/include/cereal/details/traits.hpp \
    include/third_party/cereal/include/cereal/details/util.hpp \
    include/third_party/cereal/include/cereal/external/rapidjson/error/en.h \
    include/third_party/cereal/include/cereal/external/rapidjson/error/error.h \
    include/third_party/cereal/include/cereal/external/rapidjson/internal/biginteger.h \
    include/third_party/cereal/include/cereal/external/rapidjson/internal/diyfp.h \
    include/third_party/cereal/include/cereal/external/rapidjson/internal/dtoa.h \
    include/third_party/cereal/include/cereal/external/rapidjson/internal/ieee754.h \
    include/third_party/cereal/include/cereal/external/rapidjson/internal/itoa.h \
    include/third_party/cereal/include/cereal/external/rapidjson/internal/meta.h \
    include/third_party/cereal/include/cereal/external/rapidjson/internal/pow10.h \
    include/third_party/cereal/include/cereal/external/rapidjson/internal/regex.h \
    include/third_party/cereal/include/cereal/external/rapidjson/internal/stack.h \
    include/third_party/cereal/include/cereal/external/rapidjson/internal/strfunc.h \
    include/third_party/cereal/include/cereal/external/rapidjson/internal/strtod.h \
    include/third_party/cereal/include/cereal/external/rapidjson/internal/swap.h \
    include/third_party/cereal/include/cereal/external/rapidjson/msinttypes/inttypes.h \
    include/third_party/cereal/include/cereal/external/rapidjson/msinttypes/stdint.h \
    include/third_party/cereal/include/cereal/external/rapidjson/allocators.h \
    include/third_party/cereal/include/cereal/external/rapidjson/document.h \
    include/third_party/cereal/include/cereal/external/rapidjson/encodedstream.h \
    include/third_party/cereal/include/cereal/external/rapidjson/encodings.h \
    include/third_party/cereal/include/cereal/external/rapidjson/filereadstream.h \
    include/third_party/cereal/include/cereal/external/rapidjson/filewritestream.h \
    include/third_party/cereal/include/cereal/external/rapidjson/fwd.h \
    include/third_party/cereal/include/cereal/external/rapidjson/istreamwrapper.h \
    include/third_party/cereal/include/cereal/external/rapidjson/memorybuffer.h \
    include/third_party/cereal/include/cereal/external/rapidjson/memorystream.h \
    include/third_party/cereal/include/cereal/external/rapidjson/ostreamwrapper.h \
    include/third_party/cereal/include/cereal/external/rapidjson/pointer.h \
    include/third_party/cereal/include/cereal/external/rapidjson/prettywriter.h \
    include/third_party/cereal/include/cereal/external/rapidjson/rapidjson.h \
    include/third_party/cereal/include/cereal/external/rapidjson/reader.h \
    include/third_party/cereal/include/cereal/external/rapidjson/schema.h \
    include/third_party/cereal/include/cereal/external/rapidjson/stream.h \
    include/third_party/cereal/include/cereal/external/rapidjson/stringbuffer.h \
    include/third_party/cereal/include/cereal/external/rapidjson/writer.h \
    include/third_party/cereal/include/cereal/external/rapidxml/rapidxml.hpp \
    include/third_party/cereal/include/cereal/external/rapidxml/rapidxml_iterators.hpp \
    include/third_party/cereal/include/cereal/external/rapidxml/rapidxml_print.hpp \
    include/third_party/cereal/include/cereal/external/rapidxml/rapidxml_utils.hpp \
    include/third_party/cereal/include/cereal/external/base64.hpp \
    include/third_party/cereal/include/cereal/types/concepts/pair_associative_container.hpp \
    include/third_party/cereal/include/cereal/types/array.hpp \
    include/third_party/cereal/include/cereal/types/base_class.hpp \
    include/third_party/cereal/include/cereal/types/bitset.hpp \
    include/third_party/cereal/include/cereal/types/boost_variant.hpp \
    include/third_party/cereal/include/cereal/types/chrono.hpp \
    include/third_party/cereal/include/cereal/types/common.hpp \
    include/third_party/cereal/include/cereal/types/complex.hpp \
    include/third_party/cereal/include/cereal/types/deque.hpp \
    include/third_party/cereal/include/cereal/types/forward_list.hpp \
    include/third_party/cereal/include/cereal/types/functional.hpp \
    include/third_party/cereal/include/cereal/types/list.hpp \
    include/third_party/cereal/include/cereal/types/map.hpp \
    include/third_party/cereal/include/cereal/types/memory.hpp \
    include/third_party/cereal/include/cereal/types/polymorphic.hpp \
    include/third_party/cereal/include/cereal/types/queue.hpp \
    include/third_party/cereal/include/cereal/types/set.hpp \
    include/third_party/cereal/include/cereal/types/stack.hpp \
    include/third_party/cereal/include/cereal/types/string.hpp \
    include/third_party/cereal/include/cereal/types/tuple.hpp \
    include/third_party/cereal/include/cereal/types/unordered_map.hpp \
    include/third_party/cereal/include/cereal/types/unordered_set.hpp \
    include/third_party/cereal/include/cereal/types/utility.hpp \
    include/third_party/cereal/include/cereal/types/valarray.hpp \
    include/third_party/cereal/include/cereal/types/vector.hpp \
    include/third_party/cereal/include/cereal/access.hpp \
    include/third_party/cereal/include/cereal/cereal.hpp \
    include/third_party/cereal/include/cereal/macros.hpp \
    include/third_party/gflags/include/gflags/config.h \
    include/third_party/gflags/include/gflags/gflags.h \
    include/third_party/gflags/include/gflags/gflags_completions.h \
    include/third_party/gflags/include/gflags/gflags_declare.h \
    include/third_party/gflags/include/gflags/gflags_gflags.h \
    include/third_party/glog/include/glog/log_severity.h \
    include/third_party/glog/include/glog/logging.h \
    include/third_party/glog/include/glog/logging.h.in \
    include/third_party/glog/include/glog/raw_logging.h \
    include/third_party/glog/include/glog/raw_logging.h.in \
    include/third_party/glog/include/glog/stl_logging.h \
    include/third_party/glog/include/glog/vlog_is_on.h \
    include/third_party/opencv/include/opencv/cv.h \
    include/third_party/opencv/include/opencv/cv.hpp \
    include/third_party/opencv/include/opencv/cvaux.h \
    include/third_party/opencv/include/opencv/cvaux.hpp \
    include/third_party/opencv/include/opencv/cvwimage.h \
    include/third_party/opencv/include/opencv/cxcore.h \
    include/third_party/opencv/include/opencv/cxcore.hpp \
    include/third_party/opencv/include/opencv/cxeigen.hpp \
    include/third_party/opencv/include/opencv/cxmisc.h \
    include/third_party/opencv/include/opencv/highgui.h \
    include/third_party/opencv/include/opencv/ml.h \
    include/third_party/opencv/include/opencv2/calib3d/calib3d.hpp \
    include/third_party/opencv/include/opencv2/calib3d/calib3d_c.h \
    include/third_party/opencv/include/opencv2/core/cuda/detail/color_detail.hpp \
    include/third_party/opencv/include/opencv2/core/cuda/detail/reduce.hpp \
    include/third_party/opencv/include/opencv2/core/cuda/detail/reduce_key_val.hpp \
    include/third_party/opencv/include/opencv2/core/cuda/detail/transform_detail.hpp \
    include/third_party/opencv/include/opencv2/core/cuda/detail/type_traits_detail.hpp \
    include/third_party/opencv/include/opencv2/core/cuda/detail/vec_distance_detail.hpp \
    include/third_party/opencv/include/opencv2/core/cuda/block.hpp \
    include/third_party/opencv/include/opencv2/core/cuda/border_interpolate.hpp \
    include/third_party/opencv/include/opencv2/core/cuda/color.hpp \
    include/third_party/opencv/include/opencv2/core/cuda/common.hpp \
    include/third_party/opencv/include/opencv2/core/cuda/datamov_utils.hpp \
    include/third_party/opencv/include/opencv2/core/cuda/dynamic_smem.hpp \
    include/third_party/opencv/include/opencv2/core/cuda/emulation.hpp \
    include/third_party/opencv/include/opencv2/core/cuda/filters.hpp \
    include/third_party/opencv/include/opencv2/core/cuda/funcattrib.hpp \
    include/third_party/opencv/include/opencv2/core/cuda/functional.hpp \
    include/third_party/opencv/include/opencv2/core/cuda/limits.hpp \
    include/third_party/opencv/include/opencv2/core/cuda/reduce.hpp \
    include/third_party/opencv/include/opencv2/core/cuda/saturate_cast.hpp \
    include/third_party/opencv/include/opencv2/core/cuda/scan.hpp \
    include/third_party/opencv/include/opencv2/core/cuda/simd_functions.hpp \
    include/third_party/opencv/include/opencv2/core/cuda/transform.hpp \
    include/third_party/opencv/include/opencv2/core/cuda/type_traits.hpp \
    include/third_party/opencv/include/opencv2/core/cuda/utility.hpp \
    include/third_party/opencv/include/opencv2/core/cuda/vec_distance.hpp \
    include/third_party/opencv/include/opencv2/core/cuda/vec_math.hpp \
    include/third_party/opencv/include/opencv2/core/cuda/vec_traits.hpp \
    include/third_party/opencv/include/opencv2/core/cuda/warp.hpp \
    include/third_party/opencv/include/opencv2/core/cuda/warp_reduce.hpp \
    include/third_party/opencv/include/opencv2/core/cuda/warp_shuffle.hpp \
    include/third_party/opencv/include/opencv2/core/hal/hal.hpp \
    include/third_party/opencv/include/opencv2/core/hal/interface.h \
    include/third_party/opencv/include/opencv2/core/hal/intrin.hpp \
    include/third_party/opencv/include/opencv2/core/hal/intrin_cpp.hpp \
    include/third_party/opencv/include/opencv2/core/hal/intrin_neon.hpp \
    include/third_party/opencv/include/opencv2/core/hal/intrin_sse.hpp \
    include/third_party/opencv/include/opencv2/core/hal/intrin_vsx.hpp \
    include/third_party/opencv/include/opencv2/core/opencl/runtime/autogenerated/opencl_clamdblas.hpp \
    include/third_party/opencv/include/opencv2/core/opencl/runtime/autogenerated/opencl_clamdfft.hpp \
    include/third_party/opencv/include/opencv2/core/opencl/runtime/autogenerated/opencl_core.hpp \
    include/third_party/opencv/include/opencv2/core/opencl/runtime/autogenerated/opencl_core_wrappers.hpp \
    include/third_party/opencv/include/opencv2/core/opencl/runtime/autogenerated/opencl_gl.hpp \
    include/third_party/opencv/include/opencv2/core/opencl/runtime/autogenerated/opencl_gl_wrappers.hpp \
    include/third_party/opencv/include/opencv2/core/opencl/runtime/opencl_clamdblas.hpp \
    include/third_party/opencv/include/opencv2/core/opencl/runtime/opencl_clamdfft.hpp \
    include/third_party/opencv/include/opencv2/core/opencl/runtime/opencl_core.hpp \
    include/third_party/opencv/include/opencv2/core/opencl/runtime/opencl_core_wrappers.hpp \
    include/third_party/opencv/include/opencv2/core/opencl/runtime/opencl_gl.hpp \
    include/third_party/opencv/include/opencv2/core/opencl/runtime/opencl_gl_wrappers.hpp \
    include/third_party/opencv/include/opencv2/core/opencl/runtime/opencl_svm_20.hpp \
    include/third_party/opencv/include/opencv2/core/opencl/runtime/opencl_svm_definitions.hpp \
    include/third_party/opencv/include/opencv2/core/opencl/runtime/opencl_svm_hsa_extension.hpp \
    include/third_party/opencv/include/opencv2/core/opencl/ocl_defs.hpp \
    include/third_party/opencv/include/opencv2/core/opencl/opencl_info.hpp \
    include/third_party/opencv/include/opencv2/core/opencl/opencl_svm.hpp \
    include/third_party/opencv/include/opencv2/core/utils/filesystem.hpp \
    include/third_party/opencv/include/opencv2/core/utils/logger.defines.hpp \
    include/third_party/opencv/include/opencv2/core/utils/logger.hpp \
    include/third_party/opencv/include/opencv2/core/utils/trace.hpp \
    include/third_party/opencv/include/opencv2/core/affine.hpp \
    include/third_party/opencv/include/opencv2/core/base.hpp \
    include/third_party/opencv/include/opencv2/core/bufferpool.hpp \
    include/third_party/opencv/include/opencv2/core/check.hpp \
    include/third_party/opencv/include/opencv2/core/core.hpp \
    include/third_party/opencv/include/opencv2/core/core_c.h \
    include/third_party/opencv/include/opencv2/core/cuda.hpp \
    include/third_party/opencv/include/opencv2/core/cuda.inl.hpp \
    include/third_party/opencv/include/opencv2/core/cuda_stream_accessor.hpp \
    include/third_party/opencv/include/opencv2/core/cuda_types.hpp \
    include/third_party/opencv/include/opencv2/core/cv_cpu_dispatch.h \
    include/third_party/opencv/include/opencv2/core/cv_cpu_helper.h \
    include/third_party/opencv/include/opencv2/core/cvdef.h \
    include/third_party/opencv/include/opencv2/core/cvstd.hpp \
    include/third_party/opencv/include/opencv2/core/cvstd.inl.hpp \
    include/third_party/opencv/include/opencv2/core/directx.hpp \
    include/third_party/opencv/include/opencv2/core/eigen.hpp \
    include/third_party/opencv/include/opencv2/core/fast_math.hpp \
    include/third_party/opencv/include/opencv2/core/ippasync.hpp \
    include/third_party/opencv/include/opencv2/core/mat.hpp \
    include/third_party/opencv/include/opencv2/core/mat.inl.hpp \
    include/third_party/opencv/include/opencv2/core/matx.hpp \
    include/third_party/opencv/include/opencv2/core/neon_utils.hpp \
    include/third_party/opencv/include/opencv2/core/ocl.hpp \
    include/third_party/opencv/include/opencv2/core/ocl_genbase.hpp \
    include/third_party/opencv/include/opencv2/core/opengl.hpp \
    include/third_party/opencv/include/opencv2/core/operations.hpp \
    include/third_party/opencv/include/opencv2/core/optim.hpp \
    include/third_party/opencv/include/opencv2/core/ovx.hpp \
    include/third_party/opencv/include/opencv2/core/persistence.hpp \
    include/third_party/opencv/include/opencv2/core/ptr.inl.hpp \
    include/third_party/opencv/include/opencv2/core/saturate.hpp \
    include/third_party/opencv/include/opencv2/core/softfloat.hpp \
    include/third_party/opencv/include/opencv2/core/sse_utils.hpp \
    include/third_party/opencv/include/opencv2/core/traits.hpp \
    include/third_party/opencv/include/opencv2/core/types.hpp \
    include/third_party/opencv/include/opencv2/core/types_c.h \
    include/third_party/opencv/include/opencv2/core/utility.hpp \
    include/third_party/opencv/include/opencv2/core/va_intel.hpp \
    include/third_party/opencv/include/opencv2/core/version.hpp \
    include/third_party/opencv/include/opencv2/core/vsx_utils.hpp \
    include/third_party/opencv/include/opencv2/core/wimage.hpp \
    include/third_party/opencv/include/opencv2/dnn/all_layers.hpp \
    include/third_party/opencv/include/opencv2/dnn/dict.hpp \
    include/third_party/opencv/include/opencv2/dnn/dnn.hpp \
    include/third_party/opencv/include/opencv2/dnn/dnn.inl.hpp \
    include/third_party/opencv/include/opencv2/dnn/layer.details.hpp \
    include/third_party/opencv/include/opencv2/dnn/layer.hpp \
    include/third_party/opencv/include/opencv2/dnn/shape_utils.hpp \
    include/third_party/opencv/include/opencv2/features2d/hal/interface.h \
    include/third_party/opencv/include/opencv2/features2d/features2d.hpp \
    include/third_party/opencv/include/opencv2/flann/all_indices.h \
    include/third_party/opencv/include/opencv2/flann/allocator.h \
    include/third_party/opencv/include/opencv2/flann/any.h \
    include/third_party/opencv/include/opencv2/flann/autotuned_index.h \
    include/third_party/opencv/include/opencv2/flann/composite_index.h \
    include/third_party/opencv/include/opencv2/flann/config.h \
    include/third_party/opencv/include/opencv2/flann/defines.h \
    include/third_party/opencv/include/opencv2/flann/dist.h \
    include/third_party/opencv/include/opencv2/flann/dummy.h \
    include/third_party/opencv/include/opencv2/flann/dynamic_bitset.h \
    include/third_party/opencv/include/opencv2/flann/flann.hpp \
    include/third_party/opencv/include/opencv2/flann/flann_base.hpp \
    include/third_party/opencv/include/opencv2/flann/general.h \
    include/third_party/opencv/include/opencv2/flann/ground_truth.h \
    include/third_party/opencv/include/opencv2/flann/hdf5.h \
    include/third_party/opencv/include/opencv2/flann/heap.h \
    include/third_party/opencv/include/opencv2/flann/hierarchical_clustering_index.h \
    include/third_party/opencv/include/opencv2/flann/index_testing.h \
    include/third_party/opencv/include/opencv2/flann/kdtree_index.h \
    include/third_party/opencv/include/opencv2/flann/kdtree_single_index.h \
    include/third_party/opencv/include/opencv2/flann/kmeans_index.h \
    include/third_party/opencv/include/opencv2/flann/linear_index.h \
    include/third_party/opencv/include/opencv2/flann/logger.h \
    include/third_party/opencv/include/opencv2/flann/lsh_index.h \
    include/third_party/opencv/include/opencv2/flann/lsh_table.h \
    include/third_party/opencv/include/opencv2/flann/matrix.h \
    include/third_party/opencv/include/opencv2/flann/miniflann.hpp \
    include/third_party/opencv/include/opencv2/flann/nn_index.h \
    include/third_party/opencv/include/opencv2/flann/object_factory.h \
    include/third_party/opencv/include/opencv2/flann/params.h \
    include/third_party/opencv/include/opencv2/flann/random.h \
    include/third_party/opencv/include/opencv2/flann/result_set.h \
    include/third_party/opencv/include/opencv2/flann/sampling.h \
    include/third_party/opencv/include/opencv2/flann/saving.h \
    include/third_party/opencv/include/opencv2/flann/simplex_downhill.h \
    include/third_party/opencv/include/opencv2/flann/timer.h \
    include/third_party/opencv/include/opencv2/highgui/highgui.hpp \
    include/third_party/opencv/include/opencv2/highgui/highgui_c.h \
    include/third_party/opencv/include/opencv2/imgcodecs/imgcodecs.hpp \
    include/third_party/opencv/include/opencv2/imgcodecs/imgcodecs_c.h \
    include/third_party/opencv/include/opencv2/imgcodecs/ios.h \
    include/third_party/opencv/include/opencv2/imgproc/detail/distortion_model.hpp \
    include/third_party/opencv/include/opencv2/imgproc/hal/hal.hpp \
    include/third_party/opencv/include/opencv2/imgproc/hal/interface.h \
    include/third_party/opencv/include/opencv2/imgproc/imgproc.hpp \
    include/third_party/opencv/include/opencv2/imgproc/imgproc_c.h \
    include/third_party/opencv/include/opencv2/imgproc/types_c.h \
    include/third_party/opencv/include/opencv2/ml/ml.hpp \
    include/third_party/opencv/include/opencv2/ml/ml.inl.hpp \
    include/third_party/opencv/include/opencv2/objdetect/detection_based_tracker.hpp \
    include/third_party/opencv/include/opencv2/objdetect/objdetect.hpp \
    include/third_party/opencv/include/opencv2/objdetect/objdetect_c.h \
    include/third_party/opencv/include/opencv2/photo/cuda.hpp \
    include/third_party/opencv/include/opencv2/photo/photo.hpp \
    include/third_party/opencv/include/opencv2/photo/photo_c.h \
    include/third_party/opencv/include/opencv2/shape/emdL1.hpp \
    include/third_party/opencv/include/opencv2/shape/hist_cost.hpp \
    include/third_party/opencv/include/opencv2/shape/shape.hpp \
    include/third_party/opencv/include/opencv2/shape/shape_distance.hpp \
    include/third_party/opencv/include/opencv2/shape/shape_transformer.hpp \
    include/third_party/opencv/include/opencv2/stitching/detail/autocalib.hpp \
    include/third_party/opencv/include/opencv2/stitching/detail/blenders.hpp \
    include/third_party/opencv/include/opencv2/stitching/detail/camera.hpp \
    include/third_party/opencv/include/opencv2/stitching/detail/exposure_compensate.hpp \
    include/third_party/opencv/include/opencv2/stitching/detail/matchers.hpp \
    include/third_party/opencv/include/opencv2/stitching/detail/motion_estimators.hpp \
    include/third_party/opencv/include/opencv2/stitching/detail/seam_finders.hpp \
    include/third_party/opencv/include/opencv2/stitching/detail/timelapsers.hpp \
    include/third_party/opencv/include/opencv2/stitching/detail/util.hpp \
    include/third_party/opencv/include/opencv2/stitching/detail/util_inl.hpp \
    include/third_party/opencv/include/opencv2/stitching/detail/warpers.hpp \
    include/third_party/opencv/include/opencv2/stitching/detail/warpers_inl.hpp \
    include/third_party/opencv/include/opencv2/stitching/warpers.hpp \
    include/third_party/opencv/include/opencv2/superres/optical_flow.hpp \
    include/third_party/opencv/include/opencv2/video/background_segm.hpp \
    include/third_party/opencv/include/opencv2/video/tracking.hpp \
    include/third_party/opencv/include/opencv2/video/tracking_c.h \
    include/third_party/opencv/include/opencv2/video/video.hpp \
    include/third_party/opencv/include/opencv2/videoio/cap_ios.h \
    include/third_party/opencv/include/opencv2/videoio/videoio.hpp \
    include/third_party/opencv/include/opencv2/videoio/videoio_c.h \
    include/third_party/opencv/include/opencv2/videostab/deblurring.hpp \
    include/third_party/opencv/include/opencv2/videostab/fast_marching.hpp \
    include/third_party/opencv/include/opencv2/videostab/fast_marching_inl.hpp \
    include/third_party/opencv/include/opencv2/videostab/frame_source.hpp \
    include/third_party/opencv/include/opencv2/videostab/global_motion.hpp \
    include/third_party/opencv/include/opencv2/videostab/inpainting.hpp \
    include/third_party/opencv/include/opencv2/videostab/log.hpp \
    include/third_party/opencv/include/opencv2/videostab/motion_core.hpp \
    include/third_party/opencv/include/opencv2/videostab/motion_stabilizing.hpp \
    include/third_party/opencv/include/opencv2/videostab/optical_flow.hpp \
    include/third_party/opencv/include/opencv2/videostab/outlier_rejection.hpp \
    include/third_party/opencv/include/opencv2/videostab/ring_buffer.hpp \
    include/third_party/opencv/include/opencv2/videostab/stabilizer.hpp \
    include/third_party/opencv/include/opencv2/videostab/wobble_suppression.hpp \
    include/third_party/opencv/include/opencv2/calib3d.hpp \
    include/third_party/opencv/include/opencv2/core.hpp \
    include/third_party/opencv/include/opencv2/cvconfig.h \
    include/third_party/opencv/include/opencv2/dnn.hpp \
    include/third_party/opencv/include/opencv2/features2d.hpp \
    include/third_party/opencv/include/opencv2/flann.hpp \
    include/third_party/opencv/include/opencv2/highgui.hpp \
    include/third_party/opencv/include/opencv2/imgcodecs.hpp \
    include/third_party/opencv/include/opencv2/imgproc.hpp \
    include/third_party/opencv/include/opencv2/ml.hpp \
    include/third_party/opencv/include/opencv2/objdetect.hpp \
    include/third_party/opencv/include/opencv2/opencv.hpp \
    include/third_party/opencv/include/opencv2/opencv_modules.hpp \
    include/third_party/opencv/include/opencv2/photo.hpp \
    include/third_party/opencv/include/opencv2/shape.hpp \
    include/third_party/opencv/include/opencv2/stitching.hpp \
    include/third_party/opencv/include/opencv2/superres.hpp \
    include/third_party/opencv/include/opencv2/video.hpp \
    include/third_party/opencv/include/opencv2/videoio.hpp \
    include/third_party/opencv/include/opencv2/videostab.hpp \
    include/third_party/opencv/include/opencv2/world.hpp \
    include/third_party/protobuf/include/google/protobuf/compiler/cpp/cpp_generator.h \
    include/third_party/protobuf/include/google/protobuf/compiler/csharp/csharp_generator.h \
    include/third_party/protobuf/include/google/protobuf/compiler/csharp/csharp_names.h \
    include/third_party/protobuf/include/google/protobuf/compiler/java/java_generator.h \
    include/third_party/protobuf/include/google/protobuf/compiler/java/java_names.h \
    include/third_party/protobuf/include/google/protobuf/compiler/javanano/javanano_generator.h \
    include/third_party/protobuf/include/google/protobuf/compiler/js/js_generator.h \
    include/third_party/protobuf/include/google/protobuf/compiler/js/well_known_types_embed.h \
    include/third_party/protobuf/include/google/protobuf/compiler/objectivec/objectivec_generator.h \
    include/third_party/protobuf/include/google/protobuf/compiler/objectivec/objectivec_helpers.h \
    include/third_party/protobuf/include/google/protobuf/compiler/php/php_generator.h \
    include/third_party/protobuf/include/google/protobuf/compiler/python/python_generator.h \
    include/third_party/protobuf/include/google/protobuf/compiler/ruby/ruby_generator.h \
    include/third_party/protobuf/include/google/protobuf/compiler/code_generator.h \
    include/third_party/protobuf/include/google/protobuf/compiler/command_line_interface.h \
    include/third_party/protobuf/include/google/protobuf/compiler/importer.h \
    include/third_party/protobuf/include/google/protobuf/compiler/parser.h \
    include/third_party/protobuf/include/google/protobuf/compiler/plugin.h \
    include/third_party/protobuf/include/google/protobuf/compiler/plugin.pb.h \
    include/third_party/protobuf/include/google/protobuf/io/coded_stream.h \
    include/third_party/protobuf/include/google/protobuf/io/gzip_stream.h \
    include/third_party/protobuf/include/google/protobuf/io/printer.h \
    include/third_party/protobuf/include/google/protobuf/io/strtod.h \
    include/third_party/protobuf/include/google/protobuf/io/tokenizer.h \
    include/third_party/protobuf/include/google/protobuf/io/zero_copy_stream.h \
    include/third_party/protobuf/include/google/protobuf/io/zero_copy_stream_impl.h \
    include/third_party/protobuf/include/google/protobuf/io/zero_copy_stream_impl_lite.h \
    include/third_party/protobuf/include/google/protobuf/stubs/atomic_sequence_num.h \
    include/third_party/protobuf/include/google/protobuf/stubs/atomicops.h \
    include/third_party/protobuf/include/google/protobuf/stubs/atomicops_internals_arm64_gcc.h \
    include/third_party/protobuf/include/google/protobuf/stubs/atomicops_internals_arm_gcc.h \
    include/third_party/protobuf/include/google/protobuf/stubs/atomicops_internals_arm_qnx.h \
    include/third_party/protobuf/include/google/protobuf/stubs/atomicops_internals_atomicword_compat.h \
    include/third_party/protobuf/include/google/protobuf/stubs/atomicops_internals_generic_c11_atomic.h \
    include/third_party/protobuf/include/google/protobuf/stubs/atomicops_internals_generic_gcc.h \
    include/third_party/protobuf/include/google/protobuf/stubs/atomicops_internals_mips_gcc.h \
    include/third_party/protobuf/include/google/protobuf/stubs/atomicops_internals_power.h \
    include/third_party/protobuf/include/google/protobuf/stubs/atomicops_internals_ppc_gcc.h \
    include/third_party/protobuf/include/google/protobuf/stubs/atomicops_internals_solaris.h \
    include/third_party/protobuf/include/google/protobuf/stubs/atomicops_internals_tsan.h \
    include/third_party/protobuf/include/google/protobuf/stubs/atomicops_internals_x86_gcc.h \
    include/third_party/protobuf/include/google/protobuf/stubs/atomicops_internals_x86_msvc.h \
    include/third_party/protobuf/include/google/protobuf/stubs/bytestream.h \
    include/third_party/protobuf/include/google/protobuf/stubs/callback.h \
    include/third_party/protobuf/include/google/protobuf/stubs/casts.h \
    include/third_party/protobuf/include/google/protobuf/stubs/common.h \
    include/third_party/protobuf/include/google/protobuf/stubs/fastmem.h \
    include/third_party/protobuf/include/google/protobuf/stubs/hash.h \
    include/third_party/protobuf/include/google/protobuf/stubs/logging.h \
    include/third_party/protobuf/include/google/protobuf/stubs/macros.h \
    include/third_party/protobuf/include/google/protobuf/stubs/mutex.h \
    include/third_party/protobuf/include/google/protobuf/stubs/once.h \
    include/third_party/protobuf/include/google/protobuf/stubs/platform_macros.h \
    include/third_party/protobuf/include/google/protobuf/stubs/port.h \
    include/third_party/protobuf/include/google/protobuf/stubs/scoped_ptr.h \
    include/third_party/protobuf/include/google/protobuf/stubs/shared_ptr.h \
    include/third_party/protobuf/include/google/protobuf/stubs/singleton.h \
    include/third_party/protobuf/include/google/protobuf/stubs/status.h \
    include/third_party/protobuf/include/google/protobuf/stubs/stl_util.h \
    include/third_party/protobuf/include/google/protobuf/stubs/stringpiece.h \
    include/third_party/protobuf/include/google/protobuf/stubs/template_util.h \
    include/third_party/protobuf/include/google/protobuf/stubs/type_traits.h \
    include/third_party/protobuf/include/google/protobuf/util/delimited_message_util.h \
    include/third_party/protobuf/include/google/protobuf/util/field_comparator.h \
    include/third_party/protobuf/include/google/protobuf/util/field_mask_util.h \
    include/third_party/protobuf/include/google/protobuf/util/json_util.h \
    include/third_party/protobuf/include/google/protobuf/util/message_differencer.h \
    include/third_party/protobuf/include/google/protobuf/util/time_util.h \
    include/third_party/protobuf/include/google/protobuf/util/type_resolver.h \
    include/third_party/protobuf/include/google/protobuf/util/type_resolver_util.h \
    include/third_party/protobuf/include/google/protobuf/any.h \
    include/third_party/protobuf/include/google/protobuf/any.pb.h \
    include/third_party/protobuf/include/google/protobuf/api.pb.h \
    include/third_party/protobuf/include/google/protobuf/arena.h \
    include/third_party/protobuf/include/google/protobuf/arena_impl.h \
    include/third_party/protobuf/include/google/protobuf/arenastring.h \
    include/third_party/protobuf/include/google/protobuf/descriptor.h \
    include/third_party/protobuf/include/google/protobuf/descriptor.pb.h \
    include/third_party/protobuf/include/google/protobuf/descriptor_database.h \
    include/third_party/protobuf/include/google/protobuf/duration.pb.h \
    include/third_party/protobuf/include/google/protobuf/dynamic_message.h \
    include/third_party/protobuf/include/google/protobuf/empty.pb.h \
    include/third_party/protobuf/include/google/protobuf/extension_set.h \
    include/third_party/protobuf/include/google/protobuf/field_mask.pb.h \
    include/third_party/protobuf/include/google/protobuf/generated_enum_reflection.h \
    include/third_party/protobuf/include/google/protobuf/generated_enum_util.h \
    include/third_party/protobuf/include/google/protobuf/generated_message_reflection.h \
    include/third_party/protobuf/include/google/protobuf/generated_message_table_driven.h \
    include/third_party/protobuf/include/google/protobuf/generated_message_util.h \
    include/third_party/protobuf/include/google/protobuf/has_bits.h \
    include/third_party/protobuf/include/google/protobuf/map.h \
    include/third_party/protobuf/include/google/protobuf/map_entry.h \
    include/third_party/protobuf/include/google/protobuf/map_entry_lite.h \
    include/third_party/protobuf/include/google/protobuf/map_field.h \
    include/third_party/protobuf/include/google/protobuf/map_field_inl.h \
    include/third_party/protobuf/include/google/protobuf/map_field_lite.h \
    include/third_party/protobuf/include/google/protobuf/map_type_handler.h \
    include/third_party/protobuf/include/google/protobuf/message.h \
    include/third_party/protobuf/include/google/protobuf/message_lite.h \
    include/third_party/protobuf/include/google/protobuf/metadata.h \
    include/third_party/protobuf/include/google/protobuf/metadata_lite.h \
    include/third_party/protobuf/include/google/protobuf/reflection.h \
    include/third_party/protobuf/include/google/protobuf/reflection_ops.h \
    include/third_party/protobuf/include/google/protobuf/repeated_field.h \
    include/third_party/protobuf/include/google/protobuf/service.h \
    include/third_party/protobuf/include/google/protobuf/source_context.pb.h \
    include/third_party/protobuf/include/google/protobuf/struct.pb.h \
    include/third_party/protobuf/include/google/protobuf/text_format.h \
    include/third_party/protobuf/include/google/protobuf/timestamp.pb.h \
    include/third_party/protobuf/include/google/protobuf/type.pb.h \
    include/third_party/protobuf/include/google/protobuf/unknown_field_set.h \
    include/third_party/protobuf/include/google/protobuf/wire_format.h \
    include/third_party/protobuf/include/google/protobuf/wire_format_lite.h \
    include/third_party/protobuf/include/google/protobuf/wire_format_lite_inl.h \
    include/third_party/protobuf/include/google/protobuf/wrappers.pb.h \
    Common/CommandLine.h \
    BicycleDetectionModule/BicycleDetection.h \
    DataTypes/AreaInfo.h \
    DataTypes/BaseClass.h \
    DataTypes/BicycleObjectsBuffer.h \
    DataTypes/BoardParams.h \
    DataTypes/CalibrationInfo.h \
    DataTypes/CalibrationMethod.h \
    DataTypes/DataBaseContainer.h \
    DataTypes/DatabaseController.h \
    DataTypes/DataContainer.h \
    DataTypes/DetectionParam.h \
    DataTypes/Device.h \
    DataTypes/DeviceDatabase.h \
    DataTypes/DeviceInfo.h \
    DataTypes/EventItem.h \
    DataTypes/MyString.h \
    DataTypes/ObjectBicycle.h \
    DataTypes/SystemDatabase.h \
    DataTypes/SystemInfo.h \
    DataTypes/Toolset.h \
    include/rapidjson/error/en.h \
    include/rapidjson/error/error.h \
    include/rapidjson/internal/biginteger.h \
    include/rapidjson/internal/diyfp.h \
    include/rapidjson/internal/dtoa.h \
    include/rapidjson/internal/ieee754.h \
    include/rapidjson/internal/itoa.h \
    include/rapidjson/internal/meta.h \
    include/rapidjson/internal/pow10.h \
    include/rapidjson/internal/regex.h \
    include/rapidjson/internal/stack.h \
    include/rapidjson/internal/strfunc.h \
    include/rapidjson/internal/strtod.h \
    include/rapidjson/internal/swap.h \
    include/rapidjson/msinttypes/inttypes.h \
    include/rapidjson/msinttypes/stdint.h \
    include/rapidjson/allocators.h \
    include/rapidjson/document.h \
    include/rapidjson/encodedstream.h \
    include/rapidjson/encodings.h \
    include/rapidjson/filereadstream.h \
    include/rapidjson/filewritestream.h \
    include/rapidjson/fwd.h \
    include/rapidjson/istreamwrapper.h \
    include/rapidjson/memorybuffer.h \
    include/rapidjson/memorystream.h \
    include/rapidjson/ostreamwrapper.h \
    include/rapidjson/pointer.h \
    include/rapidjson/prettywriter.h \
    include/rapidjson/rapidjson.h \
    include/rapidjson/reader.h \
    include/rapidjson/schema.h \
    include/rapidjson/stream.h \
    include/rapidjson/stringbuffer.h \
    include/rapidjson/writer.h \
    Sqlite3Manager/Assertion.h \
    Sqlite3Manager/Backup.h \
    Sqlite3Manager/Column.h \
    Sqlite3Manager/Database.h \
    Sqlite3Manager/Exception.h \
    Sqlite3Manager/sqlite3.h \
    Sqlite3Manager/SQLiteCpp.h \
    Sqlite3Manager/Statement.h \
    Sqlite3Manager/Transaction.h \
    Sqlite3Manager/Utils.h \
    Sqlite3Manager/VariadicBind.h \
    BicycleDetectionModule/BicycleDetection.h \
    ParamManager/AbstractParameter.h \
    ParamManager/LaneAreaParameter.h \
    ParamManager/ParameterManager.h \
    ParamManager/systemError.h \
    Sqlite3Manager/SQLiteCpp/Assertion.h \
    Sqlite3Manager/SQLiteCpp/Backup.h \
    Sqlite3Manager/SQLiteCpp/Column.h \
    Sqlite3Manager/SQLiteCpp/Database.h \
    Sqlite3Manager/SQLiteCpp/Exception.h \
    Sqlite3Manager/SQLiteCpp/sqlite3.h \
    Sqlite3Manager/SQLiteCpp/SQLiteCpp.h \
    Sqlite3Manager/SQLiteCpp/Statement.h \
    Sqlite3Manager/SQLiteCpp/Transaction.h \
    Sqlite3Manager/SQLiteCpp/Utils.h \
    Sqlite3Manager/SQLiteCpp/VariadicBind.h \
    Common/bicyclecommon.h \
    GoAhead/embedtls.h \
    GoAhead/goahead.h \
    GoAhead/js.h \
    GoAhead/mbedtls.h \
    GoAhead/me.h \
    GoAhead/osdep.h \
    GoAhead/WebServer.h \
    GoAhead/webapi.h \
    graphmanager.h \
    GraphManager/graphmanager.h \
    HttpService/HttpService.h \
    include/curl/curl.h \
    include/curl/curlver.h \
    include/curl/easy.h \
    include/curl/mprintf.h \
    include/curl/multi.h \
    include/curl/stdcheaders.h \
    include/curl/system.h \
    include/curl/typecheck-gcc.h \
    include/curl/urlapi.h \
    PostSsdResultsEngine/PostSsdResultsEngine.h \
    BicycleDetectionModule/bicycledetectionapi.h \
    Common/CommandParser.h \
    sdk-ezdvpp/dvpp_data_type.h \
    sdk-ezdvpp/dvpp_process.h \
    sdk-ezdvpp/dvpp_utils.h \
    video_decode/video_decode.h \
    video_decode/video_analysis_params.h \
    StreamDemux/StreamDemux.h \
    object_detection/hiai_data_sp_son.h \
    object_detection/object_detection.h \
    object_detection/thread_safe_queue.h \
    Common/video_analysis_params.h

DISTFILES += \
    graph.config \
    data/models/Resnet18.om \
    data/models/vgg_ssd_300x300.om \
    data/misc/imagenet1000_clsidx_to_labels.txt \
    graph.config.test.h264 \
    build/device/CMakeLists.txt \
    build/host/CMakeLists.txt \
    build/CMakeLists.txt \
